### ISSUE TITLE
Android Navigate Edition - No next road name/number info

### ISSUE THREAD

**Issue by BenasBruzauskas** [heremaps/here-sdk-examples#104]
Hello,

We have upgraded from Premium to Navigate Edition and there is now issue with Maneuvers.

The problem is that there is around 50% of maneuvers does have NextRoadTexts at all (empty strings), when Premium Edition did not had any of these issues.

Is it possible that Navigation Edition is not fully finished and does not have these Texts and will have in the future or we have to adapt to these changes and do not expect to receive them?

Code:
```
val nextManeuverProgress = nextManeuverList[0]
val nextManeuverIndex = nextManeuverProgress.maneuverIndex
val nextManeuver = visualNavigator.getManeuver(nextManeuverIndex)

val nextRoad: String =
  if (nextManeuver .nextRoadTexts.names.defaultValue == null) {
      nextManeuver .nextRoadTexts.numbers.defaultValue ?: "None?"
  } else {
      "unknown"
  }
```

**Comment by datasun** [comment]
PS: In your code snippet, probably you change it a bit to:

  if (nextManeuver .nextRoadTexts.names.defaultValue != null) {
      nextManeuver .nextRoadTexts.numbers.defaultValue ?: "None?"
  } else {
      "unknown"
  }

Otherwise, you will always print "unknown" when defaultValue is _not_ null.
