### ISSUE TITLE
Map route polyline is not being "Eaten" on route progress - HERE SDK Android Navigate Edition

### ISSUE THREAD

**Issue by BenasBruzauskas** [heremaps/here-sdk-examples#107]
Hello,

I tried using HERE WeGo navigation and saw, that there is Blue route polyline which is kept getting clipped behind the Navigation arrow.

I want to implement same thing in our project, but unfortunately I can't find any documentation about this feature. 

<img width="540" alt="Screenshot_20211104-113457" src="https://user-images.githubusercontent.com/45063189/140290997-37c46644-b927-485f-9d93-c9d19e6d0469.png">

The cross marked line is what I'm talking about, Is there any way to remove that tail automatically?
I am using this to show route on the map:
```
val visualNavigator: VisualNavigator
visualNavigator.route = route (calculated route)
```

**Comment by datasun** [comment]
Hello @BenasBruzauskas,

if you want to cut the already travelled path from the route polyline, you do the following:

- Disable route rendering with `visualNavigator.setRouteVisible(false)`
- Implement logic on app side to create a new `MapPolyline` that starts from the current location.
- Add the new polyline to the map, then remove the previous one. 

 Hope this helps.
