### ISSUE TITLE
Android Navigate SDK v4.9.3 Maneuver road-name / next-road-name are empty

### ISSUE THREAD

**Issue by romandanylyk** [heremaps/here-sdk-examples#109]
After successfully creating a route, I'm trying to display a list of maneuvers the user will need to make to complete the route.
While getting `[Route]` -> `getSections()` -> `getManeuvers()` -> `getRoadTexts()` or `getNextRoadTexts()` it is empty for each of the maneuver. Meaning `[RoadTexts]` `name`, `numbers` and `towards` are all empty all the time. 
Is there some additional route configuration required to receive those values?
I was able to reproduce this issue on the sample project as well - [Routing](https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/Routing).

It is worth noting, that [Maneuver] -> `getText()` returns a valid result. 
Using Navigate SDK v4.9.3
Please advice.

**Comment by datasun** [comment]
Here is an example how to get road texts during navigation, https://github.com/heremaps/here-sdk-examples/blob/4464e20cd63e99d8abb57f64530feb352f4ca21f/examples/latest/navigate/android/Navigation/app/src/main/java/com/here/navigation/NavigationExample.java#L459

For calculated routes road texts / next road texts are expected to be also available. Thanks for raising, we will investigate.

**Comment by romandanylyk** [comment]
@datasun thanks for the response. 
Looking forward to getting it resolved.

**Comment by datasun** [comment]
@romandanylyk Sadly, there is no quick fix possible. For now, we will update the documentation to make clear that the values will be always empty when retrieved from `RoutingEngine` directly. 

However, it is a missing feature, and we will try to implement for one of the next HERE SDK releases. Once this is implemented, we will communicate this via our release notes.
