### ISSUE TITLE
Android Navigate SDK: Offline mode

### ISSUE THREAD

**Issue by romandanylyk** [heremaps/here-sdk-examples#112]
I plan to add an offline mode for my app, but reading through the [offline mode documentation](https://developer.here.com/documentation/android-sdk-navigate/4.9.3.0/dev_guide/topics/offline-maps.html) I didn't find an option to turn the offline mode on. 

As specified in the documentation, once the maps are downloaded to offline mode, they won't eat data plan while viewing them. And that's cool and everything, but I would also like to prohibit using data for non-downloaded map areas. 

For example: once I have downloaded the California map package, the user is good to view the whole of California without using his data plan. But if there is an available internet connection on a device and the user panes the map to any other states - they will still be downloaded and cached. So I would like to prohibit it. Meaning if the offline mode is turned on, no matter if the internet is available or not, the app should only use downloaded/cached map data.

This is basically the same feature that the HERE We Go App has, but at this point, I didn't find a way in an SDK to turn it on / off.
Can you please specify how to do that?
Thanks.

![device-2021-11-26-133515](https://user-images.githubusercontent.com/7407504/143575622-7c16f276-59cc-4d8b-b3d9-a4f6008258aa.png)

 _Using navigate SDK v 4.9.3.0_

**Comment by datasun** [comment]
Such a global switch is not exposed yet. That means, right now it is not possible to prohibit that the map will download data. For the now the offline feature only allows to fallback to offline data - for example, when there is no internet connection available. 

However, we plan to expose such a "radio-silence" feature with one of the next releases.
