### ISSUE TITLE
Android Navigate SDK: custom cachePath / persistentMapStoragePath

### ISSUE THREAD

**Issue by romandanylyk** [heremaps/here-sdk-examples#113]
I'm trying to set a custom `cachePath` and `persistentMapStoragePath`.
According to the documentation, it should be done via `SDKNativeEngine` and `SDKOptions`.

I was trying to run such a test in [OfflineMaps](https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/OfflineMaps) sample project. 

By running the following code:
```
SDKOptions sdkOptions = new SDKOptions(
                "accessKeyId",
                "accessKeySecret",
                "/data/user/0/com.here.offlinemaps/custom-cache",
                cacheSizeInBytes,
                "/data/user/0/com.here.offlinemaps/custom-map-packages");

        SDKNativeEngine sdkNativeEngine = null;
        try {
            sdkNativeEngine = new SDKNativeEngine(sdkOptions);
        } catch (InstantiationErrorException e) {
            // Handle exception.
        }

SDKNativeEngine.setSharedInstance(sdkNativeEngine);
```

The `sdkNativeEngine.getOptions().cachePath` was actually returning a updated path (`/data/user/0/com.here.offlinemaps/custom-cache`) which is a expected behaviour. But for some reason, I didn't find that file in device storage, so it seems that it keeps using the default cache, which is only visible for rooted devices.

A similar issue is with `persistentMapStoragePath` - once I start downloading the map for offline use, it keeps using the default cache path. 

Interesting tho, that `cacheSizeInBytes` seems to work fine, I was trying to reduce it to ~50MB and it actually affects the max cache size. 

I was also trying to get cache path by calling 
`mapView.getContext().getCacheDir().getPath()`. This one seems to be related to the `mapView` only. I was trying to create it using the following constructor, but it still returns the default cache path.

```
public MapView(
   SDKNativeEngine engine, 
   android.content.Context context, 
   android.util.AttributeSet attrs, 
   int defStyleAttr)
```

I did try to set custom cache path both programmatically (as shown above) and in manifest meta-data. Unfortunately, it did not help.

```
<meta-data
    android:name="com.here.sdk.cache_path"
    android:value="/data/user/0/com.here.offlinemaps/custom-cache" />

<meta-data
    android:name="com.here.sdk.persistent_map_storage_path"
    android:value="/data/user/0/com.here.offlinemaps/custom-map-packages" />
```

Can you please provide a working sample what has the proper way to set a custom cache and persistent map path?
My case is - when there is external storage available in a device (SD card) I would like to use it as cache storage, otherwise device internal storage.

_Using navigate SDK v 4.9.3.0_

**Comment by datasun** [comment]
Thanks, @romandanylyk. We will investigate this issue on our end with #11974.

**Comment by romandanylyk** [comment]
@datasun Does the #11974 is the ticket number on your end?
Is there any way to track its status?

**Comment by datasun** [comment]
@romandanylyk It's an internal tracking number. You can track the status as part of this [issue](https://github.com/heremaps/here-sdk-examples/issues/113).

**Comment by datasun** [comment]
We cannot reproduce yet. When the path to external storage is properly retrieved from OS, it should work. Example:

```
SDKOptions sdkOptions = new SDKOptions(
  "ACCESS-KEY-ID",
  "ACCESS-KEY-SECRET",
  "/storage/0403-0201/Android/data/com.here.offlinemaps/custom-cache",
  1024*1024*64,
  "/storage/0403-0201/Android/data/com.here.offlinemaps/custom-map-packages"
);

SDKNativeEngine sdkNativeEngine = null;
try {
    sdkNativeEngine = new SDKNativeEngine(sdkOptions);
} catch (InstantiationErrorException e) {
    e.printStackTrace();
}
```

The external path can be retrieved with `Context.getExternalFilesDir()`. The internal path with `Context.getFilesDir()`.

**Comment by romandanylyk** [comment]
@datasun I just double checked the external path and can confirm that it works fine for me as well.
It looks like I had wrong external path for the first time, but now it works fine for both `cache` and `map packages cache`.
I think we can mark this issue as resolved.

**Comment by datasun** [comment]
Thanks for the update!
