### ISSUE TITLE
Timezone or UTC Offset for Place

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#115]
Hi, is there a way to get the timezone (eg "Europe/Berlin") or UTC offset of a given Place or GeoCoordinate when using the Android Navigate SDK? Thanks.

**Comment by datasun** [comment]
A location may contain a [`time`](https://developer.here.com/documentation/android-sdk-navigate/4.10.1.0/api_reference/content/com/here/sdk/core/Location.html#time). This is of Android's `Date` type, so it should give you all you need. A place may contain details such as [opening hours](https://developer.here.com/documentation/android-sdk-navigate/4.10.1.0/api_reference/content/com/here/sdk/search/OpeningHours.html#text). This you can get as localized text to print it out or in a parseable format, if needed. 

Hope this helps. Please leave a comment if not. Thanks!

**Comment by datasun** [comment]
I see. The ETA of a route is only given in seconds:

`long estimatedTravelTimeInSeconds = route.getDurationInSeconds()`

However, you get also a `Date` object for each section. E.g. `Date date = section.getArrivalTime()`. 

The last section should provide the correct `Date` for your use case.

Hope this helps.

**Comment by StefanTiess** [comment]
Hi datasun. Sorry to get back at this, but it is driving me insane. I am using the android navigate SDK and when I try to get the arrival times of sections, they absolutely do not fit the routeduration.
For example: If I plan a 5 minute route here in Germany, and I set the departure time in the route options to 5pm, then the expectation would be the arrival time is 5:05pm. However the result is 7:05pm.  Same if I don't set the departure time and let it start right now. Arrival will be 2 hours, 5minutes in the future on a 5 minute drive. So the routing engine seems to consistently add two hours on top.  The Java Date object itself has no timezone but refers to UTC. So timezone should not be an issue. At the same time, even if it would take timezone into consideration, it would take the same timezone for departure time and section arrival I assume. Still there is this 2 hour gap. Can you help me with what's going on? I sure hope this not just a brain outage on my behalf, as I tried all different kind of fixes with no change in outcome.

**Comment by datasun** [comment]
Thanks, @StefanTiess. We will try to reproduce, I have reopened the ticket. Ideally, we will extend the current example app to log also the [estimated arrival time](https://github.com/heremaps/here-sdk-examples/blob/286fb4e24c30d72e264941507db2c51557ab9cdc/examples/latest/navigate/android/Routing/app/src/main/java/com/here/routing/RoutingExample.java#L120 ).

**Comment by datasun** [comment]
@StefanTiess We have not been able to reproduce this issue. Can you give as the waypoints of a route where this is happening? Ideally, with all parameters, route options etc, so we can reliably see what goes wrong. If you have, please also provide the code snippets you use to calculate the date values. Thanks!

**Comment by datasun** [comment]
We have updated the example app to verify this. Now, also the [arrival time is logged](https://github.com/heremaps/here-sdk-examples/blob/3f2e4e95ff356b15efe58b05d608ea8cf15de0dc/examples/latest/navigate/android/Routing/app/src/main/java/com/here/routing/RoutingExample.java#L129). It works as expected. If you can still reproduce the problem, please let us know. Thanks!

**Comment by StefanTiess** [comment]
Hi datasun. Thanks for the effort in adapting the example apps. I used your routing example app to reproduce the issue.

I added the an additional line of code to the `logRouteSectionDetails` Function to track the current time on my device (set to Berlin / Germany Timezone):
 
`private void logRouteSectionDetails(Route route) {
        DateFormat dateFormat = new SimpleDateFormat("HH:mm");

        for (int i = 0; i< route.getSections().size(); i++) {
            Section section = route.getSections().get(i);

            Log.d(TAG, "Route Section : " + (i+1));
            Log.d(TAG, "Route Current Time : " + dateFormat.format(new Date()));
            Log.d(TAG, "Route Section Departure Time : " + dateFormat.format(section.getDepartureTime()));
            Log.d(TAG, "Route Section Arrival Time : " + dateFormat.format(section.getArrivalTime()));
            Log.d(TAG, "Route Section length : " +  section.getLengthInMeters() + " m");
            Log.d(TAG, "Route Section duration : " + section.getDuration().getSeconds() + " s");
        }
    }`

Still my logs read the following: 
2022-03-03 18:56:03.431 8125-8125/com.here.routing D/com.here.routing.RoutingExample: Route Current Time : 18:56
2022-03-03 18:56:03.431 8125-8125/com.here.routing D/com.here.routing.RoutingExample: Route Section Departure Time : 20:56
2022-03-03 18:56:03.431 8125-8125/com.here.routing D/com.here.routing.RoutingExample: Route Section Arrival Time : 21:00

You can see there is a 2 hour gap between the current time and the departure time of the section and I don't know where this gap comes from. This will also remain if i set a fix departure time in the CarOptions. 

If I use the `OfflineRoutingEngine` in the example app, the timings are correct btw:
2022-03-03 18:11:19.092 11353-11353/com.here.routing D/com.here.routing.RoutingExample: Route Current Time : 18:11
2022-03-03 18:11:19.093 11353-11353/com.here.routing D/com.here.routing.RoutingExample: Route Section Departure Time : 18:11
2022-03-03 18:11:19.093 11353-11353/com.here.routing D/com.here.routing.RoutingExample: Route Section Arrival Time : 18:19

**Comment by datasun** [comment]
Does it happen for you only on a device? Which device are you using and what time is set on the device? Plus: Is it also happening in simulator? And just to be sure, you have used the unchanged example app, so it happens for you with any route? Also, what HERE SDK version do you use? Thanks.

**Comment by datasun** [comment]
We confirmed that there is an issue for some regions. This will be fixed in release 4.10.5.0 - now the Date value is strictly UTC.

**Comment by StefanTiess** [comment]
Hi datasun, thank you so much for this fix. However, this brings me back to my initial point: With all time information being  strictly UTC, we would need some information about time zones of places in order to display the correct arrival time, which is also what navigation systems are there for. Imagine traveling through Canada with 6 different time zones and you are not able to predict local arrival times. Currently, we would need to rely on external libraries to get this information, which is bad. Having the time zone or at least UTC offset of a location as part of the Place or Section information would dramatically help here. I would really appreciate if you could look into this at some point  in the future. Thanks already in advance!

**Comment by datasun** [comment]
Thanks, @StefanTiess. We are aware of this problem and we are currently evaluating if the HERE SDK can improve this for one of the next releases, but I cannot promise yet. Anyway, thanks for the thorough explanation. This helps to address problems. :)
