### ISSUE TITLE
HERE SDK Orientation change too late

### ISSUE THREAD

**Issue by andreas-arkulpa** [heremaps/here-sdk-examples#122]
Hi all!

I am using HERE-Android-SDK to build a simple navigation solution with offline maps.
In order to automatically center and rotate the map (depending on location and orientation of the user) I am using the `PositioningManager` class from the HERE-SDK. It seems that the orientation update is some seconds too late when an active navigation is running.

I am using the following code snippets to do so.

```
val positioningManager = PositioningManager.getInstance()
positioningManager.addListener(WeakReference(positionListener))
positioningManager.start(PositioningManager.LocationMethod.GPS)

 var positionListener = object : PositioningManager.OnPositionChangedListener {
        override fun onPositionFixChanged(
            p0: PositioningManager.LocationMethod?,
            p1: PositioningManager.LocationStatus?
        ) {
           // do nothing here
        }

        override fun onPositionUpdated(
            method: PositioningManager.LocationMethod?,
            position: GeoPosition?,
            isMapMatched: Boolean
        ) {
            if (position == null) return
            // update map center and orientation
        }
    }
```
```
override fun onPause() {
  positioningManager.stop()
}
```
```
override fun onResume() {
  positioningManager.start(PositioningManager.LocationMethod.GPS)
}
```

Is there anything I can do to avoid the too late orientation update?
Thanks for all of your help in advance!

**Comment by datasun** [comment]
This is code for the[ Premium HERE SDK](https://developer.here.com/documentation/android-premium/3.15/content/api_reference_java/com/here/android/mpa/odml/MapLoader.html) which is not hosted here - please direct your question to our customer support. We encourage you to migrate to the Navigate Edition. Thanks!
