### ISSUE TITLE
Native Crashes in CalculateRouteCallback

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#126]
Hi, 
in my logs I see a fairly high number of native abort crashes. They seem to appear for the very most part for users in their first app session, but this can be a coincidence.

Unfortunately the Crash Logs are not that informative, but maybe you have an idea: The error occurs about 4 seconds after a truck route is asked to be calculated.

![image](https://user-images.githubusercontent.com/10030437/158600908-8654faf2-3aff-425b-a285-55bc3bba2cd4.png)

**Comment by datasun** [comment]
@StefanTiess Thanks for bringing this issue up. Such issues we cannot handle here on GitHub. Please open up a ticket through our [customer support](https://developer.here.com/help), so we can investigate this issue properly. Or raise this with your direct HERE contact, if you have. Thanks!
