### ISSUE TITLE
Error initializing OfflineMapEnginge

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#128]
Hi from time to time i get fatal crashes with an uncaught exception in the MapLoader, and the only way to fix it is to clear the app storage entirely:
`terminating with uncaught exception of type here::sdk::core::ErrorException<here::sdk::maploader::DataStoreProviderErrorCode>: Failed to initialize data store server`

Can you give a hint what causes this error and how to prevent it? I can also see this (rarely) happening to end users and it makes the app unusable for them.

**Comment by datasun** [comment]
Hi Stefan, this should have been fixed with release 4.10.1 or newer. If you already use a newer version, please contact our support team via https://developer.here.com/help. Thanks!
