### ISSUE TITLE
Android: VisualNavigator camera principal point 

### ISSUE THREAD

**Issue by romandanylyk** [heremaps/here-sdk-examples#129]
Hey,
I had an issue using `VisualNavigator`. Once I call `startRendering` it automatically resets the camera principal point to the default value, which I would like to set custom. I looks like it is happening once the new location is set to `VisualNavigator`.  
Please, let me know what is the proper way to use `VisualNavigator` with a custom map principal point. Unfortunately I did not found any suitable properties in [CameraSettings](https://developer.here.com/documentation/android-sdk-navigate/4.10.5.0/api_reference/com/here/sdk/navigation/CameraSettings.html). 
If there are any known workaround, please let me know. 

Using android navigate SDK `v.4.10.5.0`.

**Comment by datasun** [comment]
Hi Roman, you already looked at the right place. Customizing the principle point is not yet supported. However, you can render the view during navigation also yourself, since the HERE SDK supports now the `InterpolatedLocationListener` for `VisualNavigator`.

**Comment by romandanylyk** [comment]
Looks like I found it:
the required configuration to make the `InterpolatedLocationListener` work is setting
`cameraMode = CameraTrackingMode.DISABLED` along with `startRendering`
