### ISSUE TITLE
Drag item on Mapview

### ISSUE THREAD

**Issue by Schmalztopf** [heremaps/here-sdk-examples#13]
Hello,
I am just trying out the SDK Lite API and I am wondering how I can achieve to drag a MapMarker object from one place to another. I suggest, it works somehow with disabling the default onPan gesture, but actually the problem starts with picking an existing object. 

Here is my code so far:

    public void pickMarker(Point2D p) {
        map.getGestures().disableDefaultAction(GestureType.PAN);
        map.pickMapItems(p, 20f, pickMapItemsResult -> {
            if (pickMapItemsResult != null) {
                pickedMarker = pickMapItemsResult.getTopmostMarker();
            } else {
                map.getGestures().enableDefaultAction(GestureType.PAN);
            }
        });
    }

    public void dragMarker(Point2D p) {
        if (pickedMarker != null) {
            pickedMarker.setCoordinates(map.getCamera().viewToGeoCoordinates(p));
        }
    }

    public boolean releaseMarker(Point2D p) {

        map.getGestures().enableDefaultAction(GestureType.PAN);
        if (pickedMarker != null) {
            GeoCoordinates newCoordinates = map.getCamera().viewToGeoCoordinates(p);
            pickedMarker.setCoordinates(newCoordinates);
            pickedMarker = null;
            return true;
        }
        return false;
    }

while these functions are called on the three states of the onPanListener:

    mapView.getGestures().setPanListener((gestureState, point2D, point2DUpdate, v) -> {
            if (gestureState.equals(GestureState.BEGIN)) {
                mapViewUIEngine.pickMarker(point2D);
            }
            if (gestureState.equals(GestureState.UPDATE)) {
                mapViewUIEngine.dragMarker(point2DUpdate);
            }
            if (gestureState.equals(GestureState.END)) {
                if (mapViewUIEngine.releaseMarker(point2DUpdate)) {
                    regionController.movePoint(0,
                            updateNewLocation(point2D, point2DUpdate);
                }
            }
        });

Do you have a suggestion, why getTopMostMarker always returns null?

Best regards
Thomas

**Comment by datasun** [comment]
Hello Thomas, thanks for trying out the HERE SDK!

Your question is not really related to the example apps in this repository. It's more something for a general audience, please check [StackOverflow](https://stackoverflow.com/questions/tagged/here-api). 

However, your code snippets should work. If `getTopmostMarker()` returns null, then probably some other map item is picked. For example, if a `MapCircle` is picked, then `getTopmostMarker()` returns null (but that's just a guess without seeing your full code).

PS: In your `PanListener` snippet above, please make sure to use `point2D` instead of `point2DUpdate`. `point2DUpdate` contains only the translation offset since the last position. The 1st point parameter indicates the current touch point, which is what you need for dragging an item around.

**Comment by Schmalztopf** [comment]
Yes, you are right, the marker sits on the border of a polygon and the Polygon function indeed returns a Polygon object, but how can I get the marker at this point?

**Comment by datasun** [comment]
Thanks for confirming. Actually, a marker should be rendered always on top of a polygon, even if it is just the border of a polygon. We'll try to double-check if there is a potential issue.

**Comment by datasun** [comment]
@Schmalztopf We have not been able to reproduce your issue. If it is still happening, it would help if can provide the affected code snippets. Thanks.

**Comment by Schmalztopf** [comment]
Sorry, I forgot to confirm. It was like you already guessed, that if I call getTopMostMarker first, then the marker is returned. But when I call getTopMostPolygon first, getTopMostMarker will return null. I don't know, if this is intended, but for my example it I could continue working. Thanks for your support.

**Comment by datasun** [comment]
Great, thanks for confirming.
