### ISSUE TITLE
Android Navigate SDK: Feature Configuration

### ISSUE THREAD

**Issue by romandanylyk** [heremaps/here-sdk-examples#131]
I'm trying to use the feature configuration in android Navigate SDK v 4.10.5 to shrink the size of the offline map regions.
But having a fresh install on the device, the offline map size does not seem to change. 

Here is the `AndroidManifest` meta-data I added:

```
<meta-data
  android:name="com.here.sdk.feature_configuration"
  android:value="NAVIGATION, TRUCK" />
```

Are there any other configurations needed?

**Comment by datasun** [comment]
What you do is correct. As of now, the `downloadedRegions` parameter only reports the full size. Even if the actual size on disk is smaller. This is a known issue, we will hopefully fix soon.

If the actual size on disk (ie. when you check with a file browser) does not change it would be a bug.
