### ISSUE TITLE
Flutter Navigate Edition: Route Deviation Listener

### ISSUE THREAD

**Issue by santiracca** [heremaps/here-sdk-examples#132]
# Flutter Navigate Edition: Route Deviation Listener
Hello, I am having an issue with the route deviation listener for the visual navigator. In essence, the problem is that the callback for the listener never completes as the a new location update triggers the callback again and for some reason this cancels the execution of the previous callback.

I copied the example from the navigate_app, and the execution stops right before the distance in meters is calculated. Is there any reason behind this or is there something that I must modify to make it work appropriately. 

Here is a copy of my code 
```
 _visualNavigator.routeDeviationListener =
        RouteDeviationListener((RouteDeviation routeDeviation) {
      HERE.Route? route = _visualNavigator.route;
      if (route == null) {
        // May happen in rare cases when route was set to null inbetween.
        return;
      }

// Get current geographic coordinates.
      MapMatchedLocation? currentMapMatchedLocation =
          routeDeviation.currentLocation.mapMatchedLocation;
      GeoCoordinates currentGeoCoordinates = currentMapMatchedLocation == null
          ? routeDeviation.currentLocation.originalLocation.coordinates
          : currentMapMatchedLocation.coordinates;

      // Get last geographic coordinates on route.
      GeoCoordinates lastGeoCoordinatesOnRoute;
      if (routeDeviation.lastLocationOnRoute != null) {
        MapMatchedLocation? lastMapMatchedLocationOnRoute =
            routeDeviation.lastLocationOnRoute!.mapMatchedLocation;
        lastGeoCoordinatesOnRoute = lastMapMatchedLocationOnRoute == null
            ? routeDeviation.lastLocationOnRoute!.originalLocation.coordinates
            : lastMapMatchedLocationOnRoute.coordinates;
      } else {
        print(
            "User was never following the route. So, we take the start of the route instead.");
        lastGeoCoordinatesOnRoute =
            route.sections.first.departurePlace.originalCoordinates!;
      }

      int distanceInMeters =
          currentGeoCoordinates.distanceTo(lastGeoCoordinatesOnRoute) as int;
      print("RouteDeviation in meters is " + distanceInMeters.toString());
      // print("Route Deviation");
    });
```

**Comment by datasun** [comment]
Hi @santiracca, I am not sure if I fully understand the question, but the code snippet does not calculate a new route, nor does it set a new route. It only shows how to get the event.

If a deviation is detected, then there are several options how to proceed (see also the developer's guide). In general, you want to calculate a new route async and set it to the navigator.

The callback arrives on the main thread, so if the event fires again before the previous call has ended, it should be enqueued and not interrupt. 

If this does not answer the question, please print the full log output.
