### ISSUE TITLE
Traffic 

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#134]
Hi, the `queryForIncidents ` method of the Traffic Engine seems broken in the latest Android SDK Versions:
Whenever I run a query (no matter for a geoCircle or for a corridor) I get the TrafficQueryError `FAILED_TO_RETRIEVE_RESULT` with the underlying SDK Error: `traffic - Traffic error: web::json::json_exception, what: Key not found`. These Issues started appearing beginning of April.

I get the same error when using the "Traffic" example App.

**Comment by datasun** [comment]
Thanks for raising. This is a known issue we have introduced with 4.11.x. It will hopefully be fixed with the next release. The fix will be announced via release notes.
