### ISSUE TITLE
"Safety Camera ahead" Maneuver repeated endlessly until passed

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#135]
Hi, a driver reported a very annoying issue that was introduced with the 4.11.1 SDK: The "Safety Camera ahead" Maneuver Instruction is repeated non stop until the driver passed the camera. This issue is super annoying, as we use this for voice guidance as well. Also it is not reproducible in 4.11.0.

**Comment by datasun** [comment]
Hi @StefanTiess, yes, this is a known issue. We plan to fix it not before 4.11.3 release.
