### ISSUE TITLE
Edit MapImage size

### ISSUE THREAD

**Issue by alexl246** [heremaps/here-sdk-examples#138]
Take MapItemsExample as an example, MapImage currently takes the .png as its original size. Is there a way to intercept before it is posted as mapmarker and specify a size, like one can with 'iconSize: x' in Flutter for example? Thanks

```
Future<void> _addPOIMapMarker(GeoCoordinates geoCoordinates, int drawOrder) async {

    if (_poiMapImage == null) {
      Uint8List imagePixelData = await _loadFileAsUint8List('assets/poi.png');
      _poiMapImage = MapImage.withPixelDataAndImageFormat(imagePixelData, ImageFormat.png);
    }
...
```

**Comment by datasun** [comment]
Use `MapImage.withImageDataImageFormatWidthAndHeight(Uint8List imageData, ImageFormat imageFormat, int width, int height)` to set a custom size. It will also accept PNG image data
