### ISSUE TITLE
v4.11.2 Android Flutter version does not build on Flutter 3.0.0.

### ISSUE THREAD

**Issue by kleeb** [heremaps/here-sdk-examples#139]
The 4.11.2 Flutter version Android build on Flutter 3.0.0 and Dart 2.17.0 fails with:

```
e: ../plugins/here_sdk/android/src/main/kotlin/com/here/mapview/MapController.kt: (52, 42): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?
e: ../plugins/here_sdk/android/src/main/kotlin/com/here/mapview/MapController.kt: (114, 42): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?
```

FAILURE: Build failed with an exception.`

**Comment by datasun** [comment]
Thanks, @kleeb. We do not officially support Flutter 3 yet. According to latest release, the last guaranteed Flutter version is 2.10.2. We are working on Flutter 3 support, if all goes well, we will support Flutter 3 with HERE SDK v4.11.5.

**Comment by kozmabalazs** [comment]
We also face the same issue. @datasun do you have any information when the new version will be released?

**Comment by datasun** [comment]
@kozmabalazs If all goes well, we will release it already with v4.11.4, which is scheduled in 2-3 weeks.

**Comment by kamami** [comment]
When will here work with flutter 3.x.x ? We can not roll back to flutter < 3.0.0

**Comment by datasun** [comment]
Our next release 4.12.7, which will roll out next week is supporting Flutter 3.3.2.

**Comment by kamami** [comment]
Hi @datasun,
Any news about the release this week? When will it approximately happen?

**Comment by datasun** [comment]
@kamami The release is already out and added support for Flutter 3.3.2.
