### ISSUE TITLE
Having both Explore and Navigate edition in one app 

### ISSUE THREAD

**Issue by incloudss** [heremaps/here-sdk-examples#143]
Hi,

I have developed the app for motorcyclists, and my business plan considers two subscriptions for users
- freemium, lacking turn by turn navigation among others
- premium, having turn by turn navigation

Till now, i assumed that for freemium users i would have to use google maps instead, and only initialize Here Navigation SDK Maps for premium users, for costs optimization. But lately, i started to reconsider the option with having explore and navigation edition alongside in one app. 

Do you know if that is possible? I am using MAU pricing plan for Navigate edition, and would like to use Transaction plan for Explore edition. 

Two ideas popped into my mind, but i am not able to verify any of them, because i feel like the documentation is pretty humble regarding, for example counting MAUs:
1. Try to use only Navigation SDK and initialize it with different credentials, one having access to Navigate features(connected to Here Platform app id having those features enabled), and another one not having them. But i think that way i would have MAU count increased even for freemium users, because the MAU counting probably not depends on the credentials used to initialize SDK, but on the SDK internal code itself(am i wrong?). 
2. Actually reference two SDKs and load both of them into appbundle/apk, but somehow alias them and use different SDKNativeEngines to initialize Explore edition for freemium user, and Navigate edition for premium user. 

I would be really grateful for help. 

NOTE. I use Flutter SDK

**Comment by HBHXTRA** [comment]
I'd appreciate any feedback as well.
It is not sustainable to offer a free trial while being charged for it for the navigate edition.
Not offering a free trial is not an option when you consider the competition.

**Comment by moo24** [comment]
@HBHXTRA  To get access to navigate edition, you have to sign an evaluation agreement. There is no self-serve option via developer portal for this yet. You need to reach out to a sales representative, e.g. via contact form. This should not be a blocker if you are interested in using it for your application.

@incloudss  Please use https://developer.here.com/help to contact a sales representative to discuss your licensing model and SDK plan. Github is not the right place to get answers for questions on license models, especially if you want to discuss an edge case of mixing two different license models for one application. Not sure if that is supported at all.

Technically, the Navigate SDK contains all features of the Explore edition. You can also set SDK credentials at runtime programmatically and initialize only modules you need. See https://developer.here.com/documentation/android-sdk-navigate/4.11.3.0/dev_guide/topics/key-concepts.html#set-here-credentials-from-manifest-or-programmatically  
For sure, you cannot initialize the Navigation module with a Explore credential set; that won´t work as it lacks required permissions.

**Comment by HBHXTRA** [comment]
@moo24 I have access already. I was supporting the question because I have the same issue which is the economic sustainability or risk of giving free trials to my users (1 week) while Here bills me for those even they're not subscribed.
Trying to find a solution to avoid large bills while users are just trying out the app.

Also second feedback, the MAU can be counted twice if the user deletes and reinstall, there's usually a consistent ID, I think it would be a lot better and more sustainable if you guys count MAU based on that to avoid duplicate.

This is about sustainability against competition using other SDKs.

Any suggestions?

**Comment by incloudss** [comment]
@moo24 i will talk surely with sales, but the question concerns rather technical aspects of that approach, so i think it is the right place for github. If it's technically not possible, than what is the sense to reach the sales team? 

Ok, so technically speaking, if i have Navigation SDK in my app, but initialize only Explore Edition features(modules), will MAU count be increased or not?  

@HBHXTRA oh, i didn't know about counting MAUs twice when reinstalling app. Thanks for the info!

**Comment by moo24** [comment]
@incloudss  I am not an expert on the licensing terms and conditions and it is an edge case of mixing two different license models for one application. Therefore, I strongly recommend to check your use-case / business case with the experts from sales team. It might be against terms&conditions to mix two different billing models for a single app.

Technically speaking, if you are using two different HERE SDK credential sets (and initialize the SDK manually - as described here https://developer.here.com/documentation/android-sdk-navigate/4.11.3.0/dev_guide/topics/key-concepts.html#manually-initialize-the-here-sdk), you should be at least able to track the MAU for each credential-set separately. 

@HBHXTRA  I do not have any insights to your business model and I am not the right person to talk to; My recommendation is to discuss these details and the challenges you are facing with your sales representative.
