### ISSUE TITLE
heresdk.xcframework not available in downloaded demo's root folder

### ISSUE THREAD

**Issue by sranipa** [heremaps/here-sdk-examples#145]
Hi, 

I have download .zip file for this example. And in that mentioned into README.md file that

### Get Started for iOS
1. Copy the `heresdk.framework` file of the HERE SDK for iOS to the example app's root folder.
2. To run the app, you need to add your HERE SDK credentials to the `Info.plist` file.

As per first step `heresdk.framework` should be in root folder. But it is not present into root folder. Can you please help me to get `heresdk.framework`.

**Comment by sranipa** [comment]
@moo24 Can you please show the screenshot from where I will get it ?

**Comment by moo24** [comment]
@sranipa you can download it at https://platform.here.com/sdk

**Comment by sranipa** [comment]
@moo24  I already did that. I opened this page and in that I clicked on **Start with SDK** It will open one dialog and from that I pressed on **Now you are ready to download SDK** . When press on download button it will open again https://platform.here.com/sd

https://user-images.githubusercontent.com/17876312/172651848-acbcd3e3-e544-41d9-8e0b-a6f8afaab5bc.mov

k

**Comment by sranipa** [comment]
Now I got it. I was checking into https://account.here.com/  because of that now able to download SDK. Now I am able to download from https://developer.here.com/
