### ISSUE TITLE
LocationService memory leak Navigate SDK v4.11.3

### ISSUE THREAD

**Issue by VladChernetsky** [heremaps/here-sdk-examples#146]
Hi, 
I've faced a memory leak during testing the new version of Here Navigate SDK.

### Test environment:

**Project:** https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/Positioning
**Android version:**  android 11 API 30
**Here Navigate SDK version:**  heresdk-navigate-android-4.11.3.0.8814

### How to reproduce:

1. Start app
2. Rotate device (configuration changed)

### Leak canary details: 

┬───
    │ GC Root: Global variable in native code
    │
    ├─ android.telephony.TelephonyManager$1 instance
    │    Leaking: UNKNOWN
    │    Retaining 536 B in 1 objects
    │    Anonymous subclass of android.telephony.ICellInfoCallback$Stub
    │    ↓ TelephonyManager$1.val$callback
    │                         ~~~~~~~~~~~~
    ├─ com.here.odnp.cell.PlatformCellManagerApi29$ImplicitCellInfoListener instance
    │    Leaking: UNKNOWN
    │    Retaining 12 B in 1 objects
    │    ↓ PlatformCellManagerApi29$ImplicitCellInfoListener.this$0
    │                                                        ~~~~~~
    ├─ com.here.odnp.cell.PlatformCellManagerApi29 instance
    │    Leaking: UNKNOWN
    │    Retaining 5.4 kB in 141 objects
    │    mContext instance of com.here.services.internal.LocationService
    │    ↓ PlatformCellManager.mContext
    │                          ~~~~~~~~
    ╰→ com.here.services.internal.LocationService instance
    ​     Leaking: YES (ObjectWatcher was watching this because com.here.services.internal.LocationService received
    ​     Service#onDestroy() callback and Service not held by ActivityThread)
    ​     Retaining 4.1 kB in 94 objects
    ​     key = dcf73684-e0d9-46a6-b999-cc0e8b447885
    ​     watchDurationMillis = 16046
    ​     retainedDurationMillis = 11043
    ​     mApplication instance of android.app.Application
    ​     mBase instance of android.app.ContextImpl

**Comment by datasun** [comment]
Thanks for raising. Please contact us directly via help page, so we create a ticket and it's easier for you to track the progress.
