### ISSUE TITLE
Carplay and android auto examples or tips for Flutter

### ISSUE THREAD

**Issue by HBHXTRA** [heremaps/here-sdk-examples#147]
Hello,
There's no example for carplay and android auto for Flutter Navigate edition.
Any tips? 
Do I need to load the SDK on IOS and Android as well as in Flutter or any guidance?

**Comment by datasun** [comment]
Hi @HBHXTRA, please check this section in our developer's guide: https://developer.here.com/documentation/flutter-sdk-navigate/4.11.4.0/dev_guide/topics/maps.html#add-support-for-carplay-and-android-auto

Note that the HERE SDK for Flutter plugin already contains the native HERE SDK for iOS and Android.
