### ISSUE TITLE
Searching places by GeoCoordinates along GeoCorridor

### ISSUE THREAD

**Issue by zawadZwd** [heremaps/here-sdk-examples#152]
Hello, this is not an issue, but a question 😃 

Let's say I have a list of specific points on the map - mostly petrol stations and parking lots - located in a variable eg.

```dart
final listOfMyPlaces = <GeoCoordinates>[]
```

Now - I'm calculating the route between points A and B and I want to find out if there is any place from my list on the way. Is it even possible?

I'm working on Flutter Explore Edition 4.11.4.0.

**Comment by datasun** [comment]
Hi @zawadZwd, this is not easily possible, as the coordinates from the route object are map-matched to the street. If the coordinates from your list have been added as stopovers to the route, you can be sure that they are all part of the route.

What you can do is to iterated over the list of the coordinates of the route and compare them one by one with listOfMyPlaces and apply a distance check. If distance is smaller then, let's say 100m, then place is "along the way". Hope this helps.

**Comment by VladChernetsky** [comment]
Hi @zawadZwd , there is a little bit simpler way to solve this issue. 
There are tools for creating a buffer from a polyline. The buffer means polygon or geoCorridor.
Check `org.locationtech.jts.geom library`, 
`public Geometry buffer(double distance, int quadrantSegments, int endCapStyle)`
