### ISSUE TITLE
RouteHandle bound to AppID?

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#156]
Hi, a quick question: Is the routeHandle for a calculated route somewhat bound to the current API key or App ID? I wonder if I can use the routeHandle to also import Routes from other accounts (eg a third party dispatch service also using here routing APIs).

**Comment by datasun** [comment]
No, the route handle should only act as a temporary identifier for a route, it should not be bound to an account and it should be possible to share such a route handle with across users.
