### ISSUE TITLE
Do not see any map - white screen

### ISSUE THREAD

**Issue by AndrewPiterov** [heremaps/here-sdk-examples#157]
I try to run Flutter [hello_map example](https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/explore/flutter/hello_map_app) on iOS. I added `AccessKeyId` and `AccessKeySecret` as in README.md. The app successfully is launching without any errors but I do not see any map, only white screen. 

What I did wrong? or forget something?

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-07-19 at 18 40 06](https://user-images.githubusercontent.com/10525569/179804547-752bd03c-416b-4f38-b5c8-ec9c2a70c47d.png)

**Flutter doctor**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.4 21F79 darwin-arm, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by AndrewPiterov** [comment]
And on Android I have the problem as well
<img width="673" alt="Monosnap main dart — flutter_here_map 2022-07-20 11-08-13" src="https://user-images.githubusercontent.com/10525569/179944039-8513156b-8bb7-411b-a63f-4af878e3f2c2.png">

**Comment by AlbertShen0211** [comment]
+1

**Comment by AlbertShen0211** [comment]
Same problem as me

**Comment by datasun** [comment]
Please check, if you see the following (or a similar) log message "These credentials do not authorize access". Make sure you use a working set of credentials. Credentials from the 3.x editions are _not_ compatible. Credentials from the _Lite Edition_ or _Explore Edition_ are also _not_ compatible with the _Navigate Edition_.

In addition: Make sure that your device is able to make an internet connection. With slower internet connections, it may take a while until you see the first map tiles loaded. Please also make sure that your device time is set correctly. In rare cases, a wrongly set device time can lead to authentication issues with some backend services.

Hope this narrows down the issue. Please contact our HERE support if this still does not fix the issue. They can evaluate if there is an other issue with your credentials.
