### ISSUE TITLE
Failed to resolve an FFI function. 

### ISSUE THREAD

**Issue by mrqaidi** [heremaps/here-sdk-examples#161]
my code

SdkContext.init(IsolateOrigin.main);

error 
```
E/flutter (20068): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to resolve an FFI function. Perhaps `LibraryContext.init()` was not called.
E/flutter (20068): Failed to lookup symbol 'here_sdk_dart_dl_initialize': undefined symbol: here_sdk_dart_dl_initialize
E/flutter (20068): #0      catchArgumentError (package:here_sdk/src/_library_context.dart:39:5)
E/flutter (20068): #1      LibraryContext._initializeDartDl (package:here_sdk/src/_library_context.dart:120:32)
E/flutter (20068): #2      LibraryContext.init (package:here_sdk/src/_library_context.dart:89:5)
E/flutter (20068): #3      SdkContext.init (package:here_sdk/src/sdk/core/sdk_context.dart:25:20)
```

**Comment by datasun** [comment]
Can you please provide more information like, which HERE SDK edition and version you have used, the results of the `flutter doctor` and which example app you have executed. Thanks!

**Comment by datasun** [comment]
Closing, since there was no update for a week. Please leave a comment, if there is still something to check. Thanks.

**Comment by Aimanazh** [comment]
i also get the same error from this code, hope someone can help

import 'package:here_sdk/core.dart';
import 'package:here_sdk/core.engine.dart';
import 'package:here_sdk/core.errors.dart';
import 'package:here_sdk/mapview.dart';

void main() async {
  
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  SdkContext.init(IsolateOrigin.main);
  await SDKNativeEngine.sharedInstance?.dispose();
  SDKOptions sdkOptions = SDKOptions.withAccessKeySecretAndCachePath(
      "YOUR_ACCESS_KEY_ID", "YOUR_ACCESS_KEY_SECRET", "");

  SDKNativeEngine sdkNativeEngine;
  try {
    sdkNativeEngine = SDKNativeEngine(sdkOptions);
    SDKNativeEngine.sharedInstance = sdkNativeEngine;
  } on InstantiationException {
    // Handle exception.
  }
  
  runApp(MyApp());
}
