### ISSUE TITLE
INTERNAL_ERROR OfflineRoutingEngine for list of 8303 waypoints

### ISSUE THREAD

**Issue by samvgorode** [heremaps/here-sdk-examples#166]
Hi, HERE team!
Is there any way to calculate a big route? 
In my case route for 8303 waypoints returns INTERNAL_ERROR.
I've tried both OfflineRoutingEngine and RoutingEngine.

heresdk-navigate-android-4.12.4.0.9586.aar

**Comment by samvgorode** [comment]
https://developer.here.com/documentation/android-sdk-navigate/4.12.4.0/dev_guide/topics/routing.html#get-routes

Here I've found that 

By inserting an unlimited number of Waypoint items into the OfflineRoutingEngine a route can be calculated offline with the specified stopover waypoints to shape the route as close as possible as the original route.

Does this mean that if I have already downloaded offline maps - I can put  an unlimited number of Waypoint items into offline request?

**Comment by datasun** [comment]
Hi @samvgorode, it's as written in the guide,

- adding `waypoints` for route calculation: online - only around 200 are supported. Higher numbers result in an error. Offline: Unlimited - but may take a while.
- Importing routes via list of coordinates: Online: [2,50000] items are supported (note: these are not waypoints, just coordinates). Offline: Not supported.

If you experience anything different, it would be a bug. If you can confirm that, e.g. OfflineEngine fails with 8000 waypoints, please leave a reply with all details and we'll try to reproduce the issue.
