### ISSUE TITLE
initialPersistentMapStatus is PENDING_UPDATE but mapUpdateAvailability NOT_AVAILABLE

### ISSUE THREAD

**Issue by samvgorode** [heremaps/here-sdk-examples#167]
Hi, HERE team!

I have already downloaded maps: Portugal, Spain, France, Belgium, Germany, Denmark, Sweden, Finland, Lithuania, Latvia, Estonia, Poland.

When I check installation status like this

 `mapDownloader?.initialPersistentMapStatus` 
 
it returns me `PersistentMapStatus.PENDING_UPDATE`

When I try then to call 

`mapUpdater?.checkMapUpdate(CheckMapUpdateCallback { mapLoaderError, mapUpdateAvailability -> })`

then `mapUpdateAvailability == MapUpdateAvailability.NOT_AVAILABLE`

Also if I try to download one more map (Gibraltar) with this

`mapDownloader?.downloadRegions(listOf(RegionId(20558991)), object : DownloadRegionsStatusListener { }`

then in `onDownloadRegionsComplete` I've got `MapLoaderError.INTERNAL_ERROR`

Any workaround for this? Seems like there was interrupted update and offline maps do not handle this case,

heresdk-navigate-android-4.12.4.0.9586.aar

**Comment by samvgorode** [comment]
After few attempts updating maps I got  
`mapDownloader?.initialPersistentMapStatus` `PersistentMapStatus.CORRUPTED`

And the most interesting thing is that 
`mapDownloader?.repairPersistentMap` 
never returns `onCompleted `callback

**Comment by samvgorode** [comment]
Update: 
As I mentioned before, after getting `mapDownloader?.initialPersistentMapStatus` "PENDING_UPDATE", everything is broken. No possibility to download or update maps.
I've checked method `mapDownloader?.clearPersistentMapStorage` it clears maps indeed.
But right after that method `mapDownloader?.downloadRegions` returns "INTERNAL_ERROR".
After restarting an application I can download maps again.

So, workaround for initialPersistentMapStatus "PENDING_UPDATE" is just deleting all maps.

**Comment by datasun** [comment]
When initial map status is not okay, then you need to "repair" the storage. Try the following code (taken from user guide): 

```
private void checkInstallationStatus() {
    // Note that this value will not change during the lifetime of an app.
    PersistentMapStatus persistentMapStatus = mapDownloader.getInitialPersistentMapStatus();
    if (persistentMapStatus != PersistentMapStatus.OK) {
        // Something went wrong after the app was closed the last time. It seems the offline map data is
        // corrupted. This can eventually happen, when an ongoing map download was interrupted due to a crash.
        Log.d("PersistentMapStatus", "The persistent map data seems to be corrupted. Trying to repair.");

        // Let's try to repair.
        mapDownloader.repairPersistentMap(new RepairPersistentMapCallback() {
            @Override
            public void onCompleted(@Nullable PersistentMapRepairError persistentMapRepairError) {
                if (persistentMapRepairError == null) {
                    Log.d("RepairPersistentMap", "Repair operation completed successfully!");
                    return;
                }

                Log.d("RepairPersistentMap", "Repair operation failed: " + persistentMapRepairError.name());
            }
        });
    }
}
```

If this does not fix this issue, please leave a reply with detailed steps to reproduce. Thanks.
