### ISSUE TITLE
MapDownloader downloads old maps ("50.50" instead of "53.53")

### ISSUE THREAD

**Issue by samvgorode** [heremaps/here-sdk-examples#168]
When I download some regions with code
```
mapDownloader?.downloadRegions(
     listOf(RegionId(20633740), RegionId(20633737), RegionId(20633738)),
     object : DownloadRegionsStatusListener { /*some code here*/ }
)
```
Then check map version, `mapUpdater?.currentMapVersion?.stringRepresentation(",")` it is "50.50"

Then right after that there is an update to "53.53".

Why do you send outdated maps?
Is this possible to download already updated maps?

heresdk-navigate-android-4.12.4.0.9586.aar

**Comment by datasun** [comment]
What you experience is unfortunately correct behavior. The MapDownloader cannot check the server for newer map versions until it has already downloaded some regions. Then it can check if a newer version exists for these regions via checkForUpdates(). Each HERE SDK version is tailored for a specific map version, which will be initially downloaded before it can be updated.
