### ISSUE TITLE
custom LogAppender duplicate a log messages:

### ISSUE THREAD

**Issue by MyAwesomeCloud** [heremaps/here-sdk-examples#171]
Hello colleagues, 

I'm trying to set new LogAppender to SDK: 

    SDKNativeEngine.sharedInstance!.setLogAppender(
      LogAppender(
        (LogLevel logLevel, String message) {
          _logger.d('FlutterLogAppender:$logLevel, $message');
        },
      ),
    );
As stated in SDK documentation this new instance should remove previous one:

    /// Set a custom log appender to receive log message from the SDK.
    /// This overwrites a previously set appender.

But, actually log messages have repeated twice: 

    I/OLP     (12986): [INFO ] OLP - GetPartitionById not found in cache, hrn='hrn:here:data::olp-here:ocm', key='index[landmarks]@35^2'
    I/OLP     (12986): [INFO ] OLP - GetPartitionById not found in cache, hrn='hrn:here:data::olp-here:ocm', key='index[detailed_rendering]@35^2'
    I/OLP     (12986): [INFO ] OLP - GetPartitionById not found in cache, hrn='hrn:here:data::olp-here:ocm', key='index[detailed_rendering]@35^2'
    
    I/flutter (12986): [D]  FlutterLogAppender:LogLevel.logLevelInfo, [INFO ] OLP - GetPartitionById not found in cache, hrn='hrn:here:data::olp-here:ocm', key='index[landmarks]@35^2'
    I/flutter (12986): [D]  FlutterLogAppender:LogLevel.logLevelInfo, [INFO ] OLP - GetPartitionById not found in cache, hrn='hrn:here:data::olp-here:ocm', key='index[detailed_rendering]@35^2'
    I/flutter (12986): [D]  FlutterLogAppender:LogLevel.logLevelInfo, [INFO ] OLP - GetPartitionById not found in cache, hrn='hrn:here:data::olp-here:ocm', key='index[detailed_rendering]@35^2'

Can anybody suggest how to solve this issue?

**Comment by datasun** [comment]
We log this issue internally as #14685. But in the future, please contact HERE directly as this repo is only dealing with example app issues. Thanks :)
