### ISSUE TITLE
offlineSearchEngine.suggest returns position in water, so routing engine fails.

### ISSUE THREAD

**Issue by samvgorode** [heremaps/here-sdk-examples#172]
`offlineSearchEngine.suggest()` for parameters

` TextQuery("klaipeda",  TextQuery.Area(GeoCoordinates(54.6949971161, 25.2936088372)))`
 
 `SearchOptions("EN_US", 20)`
 
 Returns search results in position inside water, so route calculation fails for that positions.
 
 First two results have coordinates: Latitude - 55.6787109375, Longitude - 21.1376953125.
 
 
![image](https://user-images.githubusercontent.com/18192354/190377294-cade2e7f-7ae6-4904-89bf-f0bac3173d32.png)

 
 heresdk-navigate-android-4.12.5.0.9694.aar

**Comment by samvgorode** [comment]
Here is how google maps find Klaipeda. Marker is not in water
![image](https://user-images.githubusercontent.com/18192354/190378300-407d8eef-41d2-4a92-9b72-e392bf4a0ffb.png)

**Comment by datasun** [comment]
Thanks. To report map errors and discrepancies to HERE, go to https://www.here.com/contact and choose "Report a map error". 

If this case is specific for offline maps, then do the same, but report an error for the HERE SDK. The city's center of "klaipeda" should obviously not be in the water. ;)
