### ISSUE TITLE
VisualNavigator no way to change cameraDistanceInMeters and cameraTiltInDegrees smoothly.

### ISSUE THREAD

**Issue by samvgorode** [heremaps/here-sdk-examples#173]
Implementation of VisualNavigator does not change camera distance and camera tilt depending on speed and when driver does some maneuver.
Will this be implemented in future releases?

About current implementation. 
It is possible to change camera distance and tilt depending on speed, this code works
```
visualNavigator.cameraSettings.cameraDistanceInMeters = 150.0
visualNavigator.cameraSettings.cameraTiltInDegrees= 50.0
```
but is there any way to do it smoothly, like `mapView.camera.lookAt` works, with animation?

heresdk-navigate-android-4.12.5.0.9694.aar

**Comment by datasun** [comment]
The next HERE SDK 4.12.7.0 release will contain an auto-zoom feature that will do exactly this.

If you want to achieve a smooth animation manually in the way you have described it, you would need to update the distance and tilt values continuously in a loop. You basically would need to interpolate between start and target values. Hope this helps.
