### ISSUE TITLE
Enabling fuelDetails is not working

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#175]
When i try to activate fuel Station Details in the Search results i get an INVALID_PARAMETERS searchError and results also do not show up...

This is the code i am using for the OnlineSearchEngine.
`searchEngine.setCustomOption("show", "fuel");`

**Comment by datasun** [comment]
"fuel" = name and "show" = value, try:

`searchEngine.setCustomOption("fuel", "show");
`

Please leave a reply, if this still does not work. Thanks!

**Comment by datasun** [comment]
You can try the following:

```
searchEngine.setCustomOptions("autosuggest.show", "fuel")
searchEngine.setCustomOptions("browse.show", "fuel")
searchEngine.setCustomOptions("discover.show", "fuel")
searchEngine.setCustomOptions("lookup.show", "fuel")
```

But these name-value pairs are more like a draft. We will finalize the API and provide dedicate options. We'll announce this fix in one of the following releases.

**Comment by StefanTiess** [comment]
Hi datasun, thanks for looking into this. Unfortunately it still does not work even with the draft parameters. Instead of an INVALID_PARAMTETER when setting the custom option, i now get the SearchError `FORBIDDEN`. I guess I have to wait for the proper integration. And indication when that might be? And will you also be looking into Fuel Prices?

**Comment by datasun** [comment]
Hi @StefanTiess, unfortunately, we have bad news. It turns out that these custom features are only available upon contract with HERE, meaning your company would need access rights. We will update this in the documentation to make this more clear. 

Thanks for hint & sorry for the inconvenience.
