### ISSUE TITLE
Invisible cluster markers

### ISSUE THREAD

**Issue by WebeyeDev** [heremaps/here-sdk-examples#179]
Hi.

We use `MapMarkerCluster.WithCounter()` to display our markers in clusters. After some time we noticed that the cluster markers just disappear, when we zoom in and the cluster expands the contained markers became visible and when we zoom out and the clustering happens the markers just disappear and no clusters are visible. 

Unfortunately, we could not establish the step to reproduce, it just happened randomly.

You can find a video about the issue on the following [url](https://we.tl/t-aRNAGvS3Ih).
Here sdk version used: 4.12.5 - explore

We use the following code to init our cluster layer: 
```
Future<void> _initClusterLayer() async {
    final image = await _clusterMapIconFormatter.format(_devicePixelRatio);
    if (image == null) {
      return;
   }

    final clusterImage = MapImage.withPixelDataAndImageFormat(image, ImageFormat.png);
    final clusterImageStyle = MapMarkerClusterImageStyle(clusterImage);
    final clusterTextStyle = MapMarkerClusterCounterStyle()
      ..textColor = Colors.white
      ..maxCountNumber = 99
      ..aboveMaxText = '99+'
      ..fontSize = 40;

    final clusterLayer = MapMarkerCluster.WithCounter(clusterImageStyle, clusterTextStyle);
    _mapMarkerCluster = clusterLayer;
    _mapController.mapScene.addMapMarkerCluster(clusterLayer); 
}
```

And the following code to add our markers:
```
Future<void> _addMarkers(final Iterable<VehicleMapUIModel> data, bool showClusters) async {
    List<MapMarker> markersToAdd = [];

    for (final vehicle in data) {
      final mapMarker = await _generateMapMarker(vehicle);

      if (mapMarker != null) {
        _mapMarkerCache[vehicle.id] = mapMarker;
        markersToAdd.add(mapMarker);
      }
    }

    if (markersToAdd.isNotEmpty) {
      if (showClusters) {
        _mapMarkerCluster?.addMapMarkers(markersToAdd);
      } else {
        _mapController.mapScene.addMapMarkers(markersToAdd);
      }
    }
  }
```

**Comment by datasun** [comment]
In the linked video I do not see the number of the contained markers, is that using the same code as above? Also, can you check if you can reproduce this issue with this cluster example app: https://github.com/heremaps/here-sdk-examples/blob/0c4b3b0db8932976d2246c6f19e27d4d2c31107e/examples/latest/explore/flutter/map_items_app/lib/MapItemsExample.dart#L86

If you can reproduce this with the example app, please reopen. I would also suggest to retry with a newer HERE SDK version, 4.12.7.0, as we have done a lot of improvements and fixes recently. Thanks!

**Comment by WebeyeDev** [comment]
Thanks, the newer version works.
