### ISSUE TITLE
Disappearing map markers

### ISSUE THREAD

**Issue by WebeyeDev** [heremaps/here-sdk-examples#180]
Hi.

We use the Flutter SDK version 4.12.5 to display MapMarkers. There seems to be an issue with MapMarkers that they disappear after some time. It seems to be related to switching map layers, as it appears most frequently when we switch between satellite and normal modes. 

We found the following error in the logs:
`E/geoviz  ( 3141): [ERROR] geoviz - Can't load image asset 'MapImage5131583026138167685.png' from file or asset repository.`

You can find a video about the issue on the following [link](https://wetransfer.com/downloads/58e85f37a8b056714260f09cc0a701be20221010131555/c069350079af922647c0ee3c07fa0e7820221010131613/2c8f89).

The following code is used to change the map layer:
```
void _onMapSchemeChanged(MapSchemeUiModel mapSchemeUiModel) {
    final brightness = WidgetsBinding.instance.window.platformBrightness;
    final hereMapScheme = widget._mapSchemeFormatter.format(mapSchemeUiModel, brightness);
    _hereMapController.mapScene.loadSceneForMapScheme(hereMapScheme, (p0) {});
  }
```

Please note that when we do this, we don't modify the displayed markers at all. The markers are moving quite frequently however as they are showing the position of vehicles.

**Comment by datasun** [comment]
`MapImage5131583026138167685.png` looks like a dynamically created asset. When switching the map schemes, do you load updated assets on the fly? Also, when calling loadSceneForMapScheme(), please check in the callback if you get a `MapError`.

**Comment by WebeyeDev** [comment]
Thanks for the ideas and tips. When we updated the sdk (to: 4.12.7) this issue was solved.
