### ISSUE TITLE
How to use setTiltRangeAtZoom​ method

### ISSUE THREAD

**Issue by Strikelon** [heremaps/here-sdk-examples#183]
Hello! Could you please show some code sample, how to use method **setTiltRangeAtZoom** of class Class **MapCameraLimits**.

For example if I want the tilt be cnaged from 0 to 60 degress.

If zoom level is 20.5 or higher, tilt should be 60 degress

If zoom level is 18.5 ot less, tilt should be 0 degress.

Or this method couldn't be used for such task, and I should use something another?

Thank you!

**Comment by datasun** [comment]
Thanks, sounds like a good idea. We'll try to add an example and inform you here once done.
