### ISSUE TITLE
UI testing Activity with com.here.sdk.mapview.MapView

### ISSUE THREAD

**Issue by samvgorode** [heremaps/here-sdk-examples#188]
Hi, HERE team!
Please, give me some tips on how to test Activity or Fragment which uses MapView in layout.

Now I get this error: 

`java.lang.UnsatisfiedLinkError: No implementation found for boolean com.here.sdk.mapview.MapViewInternalHsdk.hasInstance(long) (tried Java_com_here_sdk_mapview_MapViewInternalHsdk_hasInstance and Java_com_here_sdk_mapview_MapViewInternalHsdk_hasInstance__J)`

when `mapView?.onCreate(savedInstanceState)` is called.

heresdk-navigate-android-4.12.9.0.10139.aar
heresdk-navigate-mock-4.12.9.0.10139.jar

**Comment by datasun** [comment]
Since this is not related to the example apps in this repo, please file a support request to our services help team. Please provide also more code, so they can see what you are trying to do. Thanks!

**Comment by armaker2023** [comment]
Hi @samvmisti. Did you have any answer on this? I'm also having same error
