### ISSUE TITLE
These credentials do not authorize access

### ISSUE THREAD

**Issue by nurcaglar** [heremaps/here-sdk-examples#189]
HelloMap[35936:1119439] [log] [WARN ] Configuration - Download metadata failed, error_code=6, http_status_code=403, error='{"error":"Forbidden","error_description":"These credentials do not authorize access"}

**Comment by datasun** [comment]
Hello @nurcaglar! Please make sure to follow the instructions in the developer's guide to obtain and to set valid credentials. Premium credentials will not work. Explore or Lite credentials will not work with Navigate. In case of doubt, please contact our service support team as this repo is only about example app code and not any other issues. Hope this helps at least a bit.
