### ISSUE TITLE
The map is throwing error and closing the app after a few minutes

### ISSUE THREAD

**Issue by AryanKuAg** [heremaps/here-sdk-examples#191]
![image](https://user-images.githubusercontent.com/61811630/201473608-8ca54cdd-04c5-4302-8a20-02327212d4e8.png)
![image](https://user-images.githubusercontent.com/61811630/201473616-f054a21b-8ffb-4682-956e-d10cd2df3a36.png)
Pls Help (I've purchased ur paid plan💰💰💰)!!!

**Comment by datasun** [comment]
Thanks for reporting, but please file a ticket via help desk: https://developer.here.com/help - and add more information like steps to reproduce. Then we can symbolicate the crash and look into it. This repository and its issue tracking are meant for issues with the shown example apps and this crash does not look like it is related to any example app hosted in this repository. Via help desk you can share your account, so it will be easier and faster for us to help you. Thanks!
