### ISSUE TITLE
Is there any methed to get route serialize data in routing (engine) via mobile Navigate SDK?

### ISSUE THREAD

**Issue by PHOEBEHAUNG** [heremaps/here-sdk-examples#194]
I used `Route.serializeAsync` in Premium SDK to get route data as bytearray, so that it can be passed from Activity A to Activtiy B.

But I can not find a mothed that provides the same function in Navigate SDK. 
How could I get route serialization data in Navigate SDK?

**Comment by datasun** [comment]
There is no direct support for serialization. You can contact our team directly via help desk and file a feature request. However, you can also use route handles. With route handles you have just a short string that allows to import the same route across activities. See routing guide for a usage example.
