### ISSUE TITLE
maploader::MakeTokenProvider - Failed to get the authentication token: Cancelled, error code: 9

### ISSUE THREAD

**Issue by samrakchan** [heremaps/here-sdk-examples#202]
Hi, I'm getting 

maploader::MakeTokenProvider - Failed to get the authentication token: Cancelled, error code: 9

 [WARN ] ApiLookupClientImpl - LookupApi(query/v1) unsuccessful, hrn='hrn:here:data::olp-here:ocm', error='Network request handler is empty.'

error, while integrating Navigate SDK in one of our app. Turn-by-turn navigation was working the other day but today I'm getting this error constantly.

**Comment by datasun** [comment]
Potentially, there is an issue with your credentials. Please contact us via https://developer.here.com/help.

Thanks!

**Comment by samrakchan** [comment]
Ironically it started working after including ConsentEngine, and requesting requestUserConsent().
Initially, I removed it as the comments say it's optional. 
 "Ask user to optionally opt in to HERE's data collection / improvement program"
 Seems programmatically we need to have that line of code. It's just an option for end users to opt in or out. The good thing is navigation works even you opt out.

**Comment by datasun** [comment]
Ok, thanks for the update. Indeed, it is optional to _opt in_, but asking for consent decision is mandatory. Navigation simulation works without it, but if you do not ask a user for consent, no location updates are delivered. It's ok for the user to opt out, and it will still work. Hope this helps.
