### ISSUE TITLE
Android: Thread interrupted exception while screen orientation changes Navigate SDK 

### ISSUE THREAD

**Issue by samrakchan** [heremaps/here-sdk-examples#209]
I'm getting ANR after InterruptedIOException while testing orientation changes. 

In every orientation change, I'm creating a new instance of map view since we have different layouts for each orientation. So, I guess the thread is being cancelled before it gets completed and hence the InterruptedIOException is being thrown. As logcat is not throwing the exact line of code that triggers the exception. Nevertheless, the logcat is showing the following exception

NetworkProtocol HttpClient::HttpTask::run exception: java.io.InterruptedIOException: thread interrupted
W  java.io.InterruptedIOException: thread interrupted
W  	at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
W  	at com.android.okhttp.okio.Okio$1.write(Okio.java:75)
W  	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
W  	at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
W  	at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:163)
W  	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:748)
W  	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
W  	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
W  	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
**W  	at com.here.network.NetworkProtocol$GetTask.doInBackground(Unknown Source:511)
W  	at com.here.network.NetworkProtocol$GetTask.doInBackground(Unknown Source:2)**
W  	at android.os.AsyncTask$3.call(AsyncTask.java:394)
W  	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W  	at java.lang.Thread.run(Thread.java:1012)

The issue may be related to 
https://stackoverflow.com/questions/69507103/okhttpclient-with-java-future-java-io-interruptedioexception
or 
https://stackoverflow.com/questions/49407710/getting-java-io-interruptedioexception-while-implementing-instant-search-in-andr

**Comment by datasun** [comment]
[NavigationQuickStart.zip](https://github.com/heremaps/here-sdk-examples/files/10228832/NavigationQuickStart.zip)

Please check the attached example app. It shows how to properly do orientation changes. Basically, when recreating the map view on each cycle, make sure to call `mapView.onCreate(savedInstanceState)` and re-initialize the HERE SDK.

Hope this helps.
