### ISSUE TITLE
Does the HERE maps Navigate Edition provide Signpost class like the Premium Edition does?

### ISSUE THREAD

**Issue by PHOEBEHAUNG** [heremaps/here-sdk-examples#213]
Would you provide navigation maneuver icons, like the one shown in their app?
<img width="176" alt="截圖 2023-01-17 上午12 09 21" src="https://user-images.githubusercontent.com/18407708/212722424-cbef116e-e7cb-471b-8d38-b439fcf88733.png">

Or what method or which property can I actually use to present the maneuver action(include direction, routeName, routeDirection, distance, highway exit number, highway entry number, etc)??

**Comment by datasun** [comment]
We have a signpost API that provides SVGs as shown on road shields, but what you show in the image rather looks like maneuver icons. These icons are hosted here: https://github.com/heremaps/here-icons.

For example, direction assets for your app you can find here: https://github.com/heremaps/here-icons/tree/master/icons/guidance-icons/lane-assistance/directions/set-2
.

**Comment by PHOEBEHAUNG** [comment]
Hello! Maybe I can transfer action to asset, that's okay, thanks.
But I also want to know which properties can I use to present the exit number, the exit text, the directions in Navigate Edit??

**Comment by datasun** [comment]
These assets are part of the Signpost SVG. It is meant to be overlayed with the JunctionView. You can get the SVGs for both  as String and you need a 3rd party lib to render an image out of it. You can play around with the code you see [here](https://github.com/heremaps/here-sdk-examples/blob/3ca4a7b4d58e87fdbe975424442cda26bfcf46f8/examples/latest/navigate/android/Navigation/app/src/main/java/com/here/navigation/NavigationExample.java#L522).

Currently, this feature is more in an experimental state, see also our release notes. It will be improved for the next HERE SDK releases.
