### ISSUE TITLE
The map disappears

### ISSUE THREAD

**Issue by wyzard** [heremaps/here-sdk-examples#222]
Using this code I have experiencing an issue:
https://github.com/heremaps/here-sdk-examples/blob/master/examples/latest/explore/flutter/hello_map_app/lib/main.dart.

Steps to reproduction:

- launch the app,
- put it in the background,
- turn off the display,
- wait a few seconds,
- turn the display back on,
- bring the application to the foreground.

The map then disappears and is replaced by a black rectangle.

I've created two screenshots: https://imgur.com/a/R3o9yKp.

Android 11, HERE SDK for Flutter 4.13.2. I've tried with auto-initialization and manual SDK initialization too, the result is the same.

I've found a similar issue with Google Maps:
https://stackoverflow.com/questions/59374010/flutter-googlemap-is-blank-after-resuming-from-background/59435683#59435683

https://github.com/flutter/flutter/issues/98865

**Comment by HERE-SDK-Support-Team** [comment]
Thanks!

Closing this in favor of https://github.com/heremaps/here-sdk-examples/issues/211 - it contains the same information.
