### ISSUE TITLE
Way to restrict the SearchEngine place search to specific country? without knowing geocoordinates

### ISSUE THREAD

**Issue by yuvaraj119** [heremaps/here-sdk-examples#226]
I am using Explore version of Heremaps sdk
Through SearchEngine i am trying to search list places address. I didn't find a way to restrict search limit to US country rather global.
Here we are not allowed to access users current location/gps in mobile. 
Their is 3ways below to do search, In this first two i cant use because it will require gps coordinates where the third one is not appropriate way asking user to scroll/zoom the maps.
- Search at GeoCoordinates: Performs an asynchronous search request around the specified coordinates to provide the most relevant search results nearby.
- Search in a GeoCircle area: Similar to the above, but searches for results within the specified circle area, which is defined by center geographic coordinates and a radius in meters.
- Search in a GeoBox area: Similar to the above, but searches for results within the specified rectangle area, which is defined by the South West and North East coordinates passed as parameters.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @yuvaraj119, you can search in a specific country by setting a country code to the `area`, via `TextQuery.Area.countries`. This allows to set a list of countries where the query is applied in. Note: It is not supported when using offline search via `OfflineSearchEngine`.
