### ISSUE TITLE
Background navigation is not working in here maps sdk navigation version 4.13.0

### ISSUE THREAD

**Issue by RahulFate** [heremaps/here-sdk-examples#228]
Hi Team,

I have added all required things to enable background updates and navigation. But still background navigation is not working and  I am not receiving events in background. when application going into the background mode that time mapview pause and when app is moving into the foreground then map view resumes. 

Following are the steps, I did to achieve background navigation. 

1. Enable background modes
`<key>UIBackgroundModes</key>
    <array>
        <string>location</string>
        <string>processing</string>
    </array>
`

2. Added processing more for version 13 and above 

`<key>BGTaskSchedulerPermittedIdentifiers</key>
    <array>
        <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
    </array>
`
3. Added required permissions

`<key>UIRequiredDeviceCapabilities</key>
<array>
   <string>location-services</string>
   <string>gps</string>
</array>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
   <string>This app needs to access your current location to display it on the map.</string>
<key>NSLocationWhenInUseUsageDescription</key>
   <string>This app needs to access your current location to display it on the map.</string>
<key>NSMotionUsageDescription</key>
   <string>Motion detection is needed to determine more accurate locations, when no GPS signal is found or used.</string>
`

4. Create a LocationEngine and set at least one LocationDelegate.
5. Start the LocationEngine once and set the desired accuracy level.
6. Receive Location updates and handle them in your app. 

Please suggest what I miss or need to do to achieve background navigation.

**Comment by HERE-SDK-Support-Team** [comment]
You can try this example app: https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/ios/HikingDiary ... it should run in background.
