### ISSUE TITLE
Offline maps not working

### ISSUE THREAD

**Issue by andrei200287** [heremaps/here-sdk-examples#230]
Downloaded heresdk-explore-ios-examples-4.13.5.0 and can not find example of OfflineMaps. Tried run OfflineMaps using sdk version 4.13.5.0, got errors: Cannot find type 'MapDownloader' in scope, etc.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @andrei200287, the example is only available for the Navigate Edition, it is [here](https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/ios/OfflineMaps). 

The `MapDownloader` class is not available for the Explore Edition.

Take a look at this overview: https://developer.here.com/documentation/ios-sdk-explore/4.13.5.0/dev_guide/index.html
