### ISSUE TITLE
EXC_BAD_ACCESS (KERN_INVALID_ADDRESS) here_sdk_harp_plugins_omv_bindingsListOf_sdk_mapview_MapMarker_get_value_nullable

### ISSUE THREAD

**Issue by tarasChernysh** [heremaps/here-sdk-examples#233]
I can't reproduce that crash, but I see these logs in Crashlytic.
It's not from an example app. 

I see this crash logs: 

com.apple.main-thread
0  libsystem_kernel.dylib         0x1558 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8078 _pthread_cond_wait + 1232
2  libc++.1.dylib                 0x12f8c std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  heresdk                        0x2541ec here_sdk_std_string_get_value + 1476
4  heresdk                        0x35a6b0 here_sdk_harp_plugins_omv_bindingsListOf_sdk_mapview_MapMarker_get_value_nullable + 710908
5  heresdk                        0x359bc4 here_sdk_harp_plugins_omv_bindingsListOf_sdk_mapview_MapMarker_get_value_nullable + 708112
6  heresdk                        0x380478 here_sdk_harp_plugins_omv_bindingsListOf_sdk_mapview_MapMarker_get_value_nullable + 865988
7  heresdk                        0x360874 here_sdk_harp_plugins_omv_bindingsListOf_sdk_mapview_MapMarker_get_value_nullable + 735936
8  heresdk                        0x368b94 here_sdk_harp_plugins_omv_bindingsListOf_sdk_mapview_MapMarker_get_value_nullable + 769504
9  heresdk                        0x125ad0 here_sdk_sdk_mapview_MapScheme_get_value_nullable + 33992
10 heresdk                        0x4a1a4 (Missing UUID ce96595d9e9036638f1edebd0abef181)
11 heresdk                        0x4a0ec (Missing UUID ce96595d9e9036638f1edebd0abef181)
12 heresdk                        0xd5f1c (Missing UUID ce96595d9e9036638f1edebd0abef181)
13 heresdk                        0xd8050 (Missing UUID ce96595d9e9036638f1edebd0abef181)
14 heresdk                        0xd8120 (Missing UUID ce96595d9e9036638f1edebd0abef181)
15 heresdk                        0xd51d0 (Missing UUID ce96595d9e9036638f1edebd0abef181)
16 ...                            0x175f60 MapViewController.setupUI() + 173 (MapViewController.swift:173)
17 ....                            0x175544 MapViewController.setup() + 162 (MapViewController.swift:162)
18 ...                            0x175730 @objc MapViewController.viewDidLoad() + 134 (MapViewController.swift:134)
19 UIKitCore                      0x37dd84 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 84
20 UIKitCore                      0x1ac10 -[UIViewController loadViewIfRequired] + 712
21 UIKitCore                      0x1a928 -[UIViewController view] + 24
22 ...                            0x1369f4 MapParentViewController.addMapVC() + 14 (UIViewController+Extensions.swift:14)
23 ...                            0x135570 MapParentViewController.setupUI() + 136 (MapParentViewController.swift:136)
24 ...                            0x13514c MapParentViewController.viewDidLoad() + 105 (MapParentViewController.swift:105)
25 ...                            0x1361b4 @objc MapParentViewController.viewDidLoad() + 753520 (<compiler-generated>:753520)
26 UIKitCore                      0x37dd84 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 84
27 UIKitCore                      0x1ac10 -[UIViewController loadViewIfRequired] + 712
28 UIKitCore                      0x2dc7ac -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 124
29 UIKitCore                      0x1a40cc -[UINavigationController _startTransition:fromViewController:toViewController:] + 196
30 UIKitCore                      0x1a357c -[UINavigationController _startDeferredTransitionIfNeeded:] + 608
31 UIKitCore                      0x1a2bcc -[UINavigationController __viewWillLayoutSubviews] + 96
32 UIKitCore                      0x1a2b30 -[UILayoutContainerView layoutSubviews] + 172
33 UIKitCore                      0x4ef4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1920
34 QuartzCore                     0xa4ac CA::Layer::layout_if_needed(CA::Transaction*) + 500
35 QuartzCore                     0x1da28 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 148
36 QuartzCore                     0x2ee54 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 444
37 QuartzCore                     0x5e3c0 CA::Transaction::commit() + 648
38 QuartzCore                     0x48374 CA::Transaction::flush_as_runloop_observer(bool) + 88
39 UIKitCore                      0x4fd5f4 _UIApplicationFlushCATransaction + 52
40 UIKitCore                      0x64de00 _UIUpdateSequenceRun + 84
41 UIKitCore                      0xcb1944 schedulerStepScheduledMainSection + 144
42 UIKitCore                      0xcb0ea0 runloopSourceCallback + 92
43 CoreFoundation                 0xd3208 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
44 CoreFoundation                 0xdf864 __CFRunLoopDoSource0 + 176
45 CoreFoundation                 0x646c8 __CFRunLoopDoSources0 + 244
46 CoreFoundation                 0x7a1c4 __CFRunLoopRun + 828
47 CoreFoundation                 0x7f4dc CFRunLoopRunSpecific + 612
48 GraphicsServices               0x135c GSEventRunModal + 164
49 UIKitCore                      0x39d37c -[UIApplication _run] + 888
50 UIKitCore                      0x39cfe0 UIApplicationMain + 340
51 ....                            0x6480 main + 11 (AppDelegate.swift:11)
52 ???                            0x1e0ea4dec (Missing)

```
func setupUI() {
        self.mapView = MapView(frame: .zero)
        self.mapView.translatesAutoresizingMaskIntoConstraints = false
        self.mapView.gestures.panDelegate = self
        self.mapView.gestures.tapDelegate = self
        self.mapView.camera.addDelegate(self)
        self.mapView.gestures.disableDefaultAction(forGesture: .twoFingerPan)
        self.mapView.gestures.disableDefaultAction(forGesture: .pinchRotate)
        let pinchGesture = UIPinchGestureRecognizer(target: self, action: #selector(self.pinchRecognized(_:)))
        self.mapView.isUserInteractionEnabled = true
        self.mapView.addGestureRecognizer(pinchGesture)
        self.view.addSubview(self.mapView)
        self.mapView.addSubview(someView1)
        self.mapView.addSubview(someView2)
        
        NSLayoutConstraint.activate([
            
            self.mapView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor),
            self.mapView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor),
            self.mapView.topAnchor.constraint(equalTo: self.view.topAnchor),
            self.mapView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor) ])
}

```
HereSDK v4.11.3.0
Xcode 14.2
iOS 16.3.1, 16.4.1
iPhone 14, 13 mini
macOS Ventura 13.0.1

The whole stack trace is here 
[traceLogs.txt](https://github.com/heremaps/here-sdk-examples/files/11331733/traceLogs.txt)

**Comment by HERE-SDK-Support-Team** [comment]
Hi @tarasChernysh, please follow our [bug reporting guideline](https://developer.here.com/documentation/android-sdk-navigate/dev_guide/topics/key-concepts.html#getting-help-when-bugs-occur). Is this a crash happening with the example apps? Which steps lead to the crash? If it is not reproducible with the example app, it is recommended to contact our [support team](https://developer.here.com/help). Thank you.

**Comment by tarasChernysh** [comment]
I have updated issue

**Comment by HERE-SDK-Support-Team** [comment]
Thanks for reporting. Internal ticket number: #17338.

**Comment by HERE-SDK-Support-Team** [comment]
This crash was identified to come from 4.11.3 Explore Edition. The code base was refactored since 4.11.3 to not use the main thread for such scenarios. If you switch to a newer HERE SDK version like 4.14.1, the crash should no longer occur.
