### ISSUE TITLE
[iOS] HereSDK Explorer Version 4.14.0.0 build crash 

### ISSUE THREAD

**Issue by CatalinNDKV** [heremaps/here-sdk-examples#243]
Hello,

I am trying to integrate the new HereSDK Explorer version and I am getting Undefined symbol: _$sSSs5Error7heresdkMc when trying to run the project.

HereSDK Explorer Version: 4.14.0.0 
Xcode version: 14.2
Simulator iOS Version: 16.2.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @CatalinNDKV, can you provide the exact steps you did to build an example app? And which example app did you try? In case of doubt, please follow these [guidelines](https://developer.here.com/documentation/ios-sdk-explore/4.14.2.0/dev_guide/topics/quick-start.html#try-the-example-apps).

**Comment by CatalinNDKV** [comment]
Hello,

I tried using the 4.14.1.0 version of HereSDK for my project. The project already had included a HereSDK and I tried to update to the newest version and got this error. I followed the guidelines, tried to exclude arm64, tried to run in Rosseta mode, validate workspace, run on simulator and a real device, run on M1 chip laptop and on a Intel laptop and the error still persisted.

**Comment by HERE-SDK-Support-Team** [comment]
Closing, as there was no update since a while. If you have more information to share, please leave a reply. Thanks!
