### ISSUE TITLE
CalculateCarRoute from OfflineRoutingEngine crashing

### ISSUE THREAD

**Issue by pedroicandido** [heremaps/here-sdk-examples#245]
Hey guys! I'm trying to use the offline routing engine because I need to use an unlimited number of waypoints, but when the first waypoint is too far from the second it shows an internal error and this doesn't happen in the Routing Engine. I couldn't find anything in the documentation that explained about it, is this behavior normal?

**Comment by HERE-SDK-Support-Team** [comment]
Hi @pedroicandido, thanks for raising. This sounds not as expected. Can you paste the code you use to calculate the route? And also the affected waypoint data, so that we can replicate the issue on our end. In addition, please let us know the regions you have installed. Thanks!

**Comment by pedroicandido** [comment]
Hey, guys! I'm sorry, but I already managed to fix it! Some of the settings for downloading the map were wrong! But I fixed it and now it's working properly!
