### ISSUE TITLE
Offline routing engine does not render line correctly

### ISSUE THREAD

**Issue by pedroicandido** [heremaps/here-sdk-examples#246]
Hey guys, how are you? I'm having a problem using the Offline Routing Engine. I'll try to give as much detail as possible so you can tell me if the problem is in the SDK or it's just its default behavior. I work for a public transport company (bus). We have a website where routes with several stopping points are created, and we need to show this route exactly the same in the application so that the driver can take this route. In theory there could be no difference between the routes, but in some cases the sdk calculates a different route from the one on the website. We tried to use importRoute or importRouteFromHandle, but in these methods unfortunately it is not possible to add waypoints. For this we are trying to use the offline routing engine, as this allows us to use an unlimited amount of points, and in theory make the route as faithful as possible to the one on the website. However, when we try to use the offline engine, it always shows us a route with several different streets intertwined with each other.

Test data:
- Download map of Brazil
- I'll leave attached a list of latitude and longitude for testing (which are the same ones I'm using in an application route), and I'll also leave an image of how it should look;

[waypoints.docx](https://github.com/heremaps/here-sdk-examples/files/11654433/waypoints.docx)

- This is how the line should appear:
<img width="986" alt="Captura de Tela 2023-06-05 às 16 11 37" src="https://github.com/heremaps/here-sdk-examples/assets/49328524/3e76d8be-293e-4229-b9f7-7e5ea14ca49c">

- This is how it looks in the application using offline routing engine:
<img width="339" alt="Captura de Tela 2023-06-05 às 16 21 07" src="https://github.com/heremaps/here-sdk-examples/assets/49328524/d05cde69-a0a5-4d19-8978-b20d8796c608">

**Comment by HERE-SDK-Support-Team** [comment]
Hi @pedroicandido, thanks for the report. Maybe you can let us know some more information. The website you are using is a non-HERE website or are you using the HERE Routing API to calculate the routes via web? 

If your use cases is for buses, then ideally, you would calculate the Route from A to B and insert the bus stops as `stopover` waypoints. These are guaranteed to be passed by. And up to 200 should work. Have you tried this? Indeed the route between the waypoints may not be exactly like on the website, but this may be natural, as the HERE routing backend will take current time and traffic situation into account. This you can eliminate if you do the same with the OfflineRoutingEngine.

From the [waypoints.docx](https://github.com/heremaps/here-sdk-examples/files/11654433/waypoints.docx) it looks like you insert the shape of the route and not only the bus stops?

However, it would help if you can pass the code you use for the `OfflineRoutingEngine`. The image indicates a detour around Borda do Campo.

**Comment by HERE-SDK-Support-Team** [comment]
Closing since there was no update. Please leave a reply in case of an update. Thanks!
