### ISSUE TITLE
Polylines

### ISSUE THREAD

**Issue by alexl246** [heremaps/here-sdk-examples#247]
Is there a way to place 2 separate polyline's on a HERE map using the basic `mapScene.addMapPolyline(polyline)` method?

Thanks

**Comment by HERE-SDK-Support-Team** [comment]
Hi @alexl246, yes, of course. For example, check the **Routing** example app from this repo: When you do not clear the map view, then each new route is added as a separate polyline. 

`addMapPolyline()` requires a `MapPolyline` instance. Any new instance will be a separate polyline on the map.

Check the [Map Items](https://developer.here.com/documentation/ios-sdk-navigate) guide for more details.
