### ISSUE TITLE
Voice Assistant is not working in Navigate Edition

### ISSUE THREAD

**Issue by RahulFate** [heremaps/here-sdk-examples#248]
Hi Team,

I used a helper class called VoiceAssistant that wraps a Text-To-Speech engine to speak the maneuver notification.  And implement following delegate

visualNavigator.maneuverNotificationDelegate = self

...

// Conform to ManeuverNotificationDelegate.
// Notifies on voice maneuver messages.
func onManeuverNotification(_ text: String) {
    voiceAssistant.speak(message: text)
}

And used setupVoiceGuidance function & getLanguageCodeForDevice but not received voice instruction.   Kindly help me out to fix this issue.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @RahulFate, it looks like you are using the [VoiceAssistant](https://github.com/heremaps/here-sdk-examples/blob/master/examples/latest/navigate/ios/Navigation/Navigation/VoiceAssistant.swift) from the [Navigation](https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/ios/Navigation) example app in your own app? 

If that should be that case, try to execute the example app (unmodified) and you will hear the voices playing. If this does not work, then check your simulator settings.

From the code snippets you provided it is impossible to tell what is going wrong in your implementation. One common mistake is that your delegate is not adopting `ManeuverNotificationDelegate`. So, this could be one thing to check first.

**Comment by RahulFate** [comment]
Hi,

I execute the unmodified example of Navigation app, there also it is not heard.

**Comment by HERE-SDK-Support-Team** [comment]
Please try it on a real device. It could be that the simulator or your MacBook is having an issue with sound. On a real device it will work. You can also cross-check with another app that outputs sound to verify everything is set-up properly. If there are still issue, let us know the device and the HERE SDK version and the iOS version. Thank you.
