### ISSUE TITLE
4.14.5 not yet downloadable

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#253]
Hi,

as the last Version 4.14.4 made the "trailing location indicator" issue in the visual navigator worse, and it seems to be fixed in the new SDK Version according to changelog, when will the 4.14.5 be downloadable on the here platform? As of now, only the 4.14.4 is offered.

Thanks,
Stefan

**Comment by HERE-SDK-Support-Team** [comment]
4.14.5.0 is currently being tested. We expect to ship it in a few days. The next major release 4.15.0 will also come soon. The location indicator issues have been already marked as fixed. for 4.14.5.0.
