### ISSUE TITLE
4.14.5 PictureInPicture Mode issue

### ISSUE THREAD

**Issue by StefanTiess** [heremaps/here-sdk-examples#255]
Hi, 

in the new 4.14.5 SDK Version for Android the mapView has big issues when the Activity goes to pictureInPicture Mode during visual navigation or when resuming back from pictureInPictureMode to a fullscreen activity: In both cases the mapview retains the size of the previous state, leading to layout glitches and ANRs. This behavior was not observable in previous SDK Versions.

This is also reproducible in the NavigationExample if you add some basic PictureInPicture capability by adding "supportsPictureInPicture" flag to the main activity in AndroidManifest and overriding onUserLeaveHint 

```
 @Override
    protected void onUserLeaveHint() {
        super.onUserLeaveHint();
        PackageManager pm = getPackageManager();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            if (!pm.hasSystemFeature(PackageManager.FEATURE_PICTURE_IN_PICTURE)) return;

            try {
                PictureInPictureParams pipp = new PictureInPictureParams.Builder()
                        .setAspectRatio(new Rational(1, 1))
                        .build();

                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                    pipp = new PictureInPictureParams.Builder()
                            .setAspectRatio(new Rational(1, 1))
                            .setSeamlessResizeEnabled(true)
                            .setAutoEnterEnabled(false)
                            .build();
                }

                enterPictureInPictureMode(pipp);

            } catch (Throwable e) {
                Log.e(TAG, "Error", e);

            }


        }
    }
```

Anything I need to adapt, or is this a fix on you side?

**Comment by HERE-SDK-Support-Team** [comment]
Hi @StefanTiess, 

this should work out-of-the-box. 

Make sure to **not** pause **MapView** when it is being displayed in [PiP](https://developer.android.com/develop/ui/views/picture-in-picture) mode.  If this does not fix the issue for you, please leave a reply, thanks!
