### ISSUE TITLE
showing X/Y not physical address 

### ISSUE THREAD

**Issue by bongo3331** [heremaps/here-sdk-examples#256]
when raising Here in android auto it navigates to address based on X/Y co-ordinates. We require it to show the physical street address. 
How can this be achieved 

Android 13

**Comment by HERE-SDK-Support-Team** [comment]
Hi @bongo3331, it sounds like you want to do reveres geocoding. Take a look at this guide: https://developer.here.com/documentation/android-sdk-navigate/4.14.5.0/dev_guide/topics/search.html#reverse-geocode-an-address-from-geographic-coordinates

Please leave a reply if this is not sufficient or if you have more questions. Thanks!
