### ISSUE TITLE
iOS Navigate SDK: How to download image of route between given source location and destination location swift 

### ISSUE THREAD

**Issue by RahulFate** [heremaps/here-sdk-examples#261]
Hi Team,

I would like to download static image of drawn route on map view for given source and destination location coordinates. Please suggest , how I can achieve this.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @RahulFate, with the `MapView` you can take a screenshot of current map view. Note that this does not work when the map view is currently not visible, for example, when an application is running in background - even if `MapView.pause()` was not called. Take a look at the API Reference: https://developer.here.com/documentation/ios-sdk-navigate/api_reference/Classes/MapView.html#%2Fs:7heresdk7MapViewC14takeScreenshot8callbackyySo7UIImageCSgc_tF
