### ISSUE TITLE
[Question] Do you have offline map support?

### ISSUE THREAD

**Issue by shinriyo** [heremaps/here-sdk-examples#265]
Is it possible to download maps with this SDK?
Also, I would like the downloaded data to be stored for at least one month.

**Comment by shinriyo** [comment]
https://developer.here.com/documentation/ios-premium/dev_guide/topics/map-data.html

**Comment by shinriyo** [comment]
It says persistent. So does it keep data until deleting?

**Comment by HERE-SDK-Support-Team** [comment]
Hi @shinriyo, you link is for the _Premium Edition_. 

But yes, for the Navigate Edition, we fully support your use case. Read more about this here: https://developer.here.com/documentation/ios-sdk-navigate/dev_guide/topics/maps.html#offline-maps
