### ISSUE TITLE
[Question] Do you have localization features?

### ISSUE THREAD

**Issue by shinriyo** [heremaps/here-sdk-examples#266]
Does this SDK support map localization features? 
I assume it supports English, but I need support for Japanese, Korean, Simplified Chinese, and Traditional Chinese.

Thank you

**Comment by shinriyo** [comment]
https://developer.here.com/documentation/android-premium/dev_guide/topics/coverage-label-languages.html

I tried

```
mapView.inputView?.inputViewController?.primaryLanguage = "JPN"
```

and

```
mapView.inputView?.inputViewController?.primaryLanguage = "jJA"
```

but it can't work

**Comment by shinriyo** [comment]
How confusing is this documentation?

**Comment by HERE-SDK-Support-Team** [comment]
Hi @shinriyo, we support all the listed map languages and many more. Usage example for the _Navigate Edition_ is shown here: https://developer.here.com/documentation/ios-sdk-navigate/dev_guide/topics/maps.html#set-a-map-language 

Note that your links are for the legacy edition. Please consider to use the 4.x editions instead. Thanks!
