### ISSUE TITLE
Incomplete information in "Get Started for Flutter"

### ISSUE THREAD

**Issue by xobs** [heremaps/here-sdk-examples#269]
In the "Get Started for Flutter" section at https://github.com/heremaps/here-sdk-examples/tree/master#get-started-for-flutter the user is instructed to download the SDK and then unzip it. This is missing a step.

The SDK file that is downloaded is named something along the lines of `heresdk-navigate-flutter-4.15.4.0.4097.zip`. If one were to do as instructed, the contents of this zipfile would be extracted to `plugins/here_sdk`. This is incorrect.

The actual instructions should read:

1. Unzip the HERE SDK for Flutter plugin, and then extract the contents of the `.tar.gz file` to a new folder called `here_sdk`. Place the `here_sdk` folder unto the `plugins` folder of the example app project: 'here_sdk': hello_map/plugins/here_sdk

**Comment by HERE-SDK-Support-Team** [comment]
Thanks, we have updated the GitHub page to make this more clear. Please reopen, if you have found another issue. Thank you!
