### ISSUE TITLE
Missing tests examples for Flutter

### ISSUE THREAD

**Issue by oguibueno** [heremaps/here-sdk-examples#27]
There's some documentation about tests for Flutter?

I couldn't find any example for that.

**Comment by datasun** [comment]
At the moment, this is not planned. This repo hosts only example apps that show how to _use_ the APIs of HERE SDK for Flutter. There are no examples that show how to write tests for your apps. Client-side tests should focus on the app logic itself and there are useful resources for this on the official Flutter pages. Of course, the HERE SDK itself is tested intensely internally, so there should be no need to write tests that verify the SDK's behavior. And the contained app logic of the example apps is rather simple.
