### ISSUE TITLE
Flutter navigation edition: how to add label text on marker

### ISSUE THREAD

**Issue by ocsimulator** [heremaps/here-sdk-examples#271]
I  can't find way to add label on marker. I want to add sequence number on marker.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @ocsimulator, a marker is basically just an image. So, you cannot add a label. What you can do is to use `MapViewPins` for this purpose. This are basically Flutter widgets you can "pin" to the map. See here: https://developer.here.com/documentation/flutter-sdk-navigate/dev_guide/topics/map-items.html#add-map-view-pins
