### ISSUE TITLE
Get SVG maneuver icons from HERE Icon Library

### ISSUE THREAD

**Issue by samvmisti** [heremaps/here-sdk-examples#272]
In the latest HERE SDK examples there is a project Rerouting.

heresdk-navigate-android-4.15.4.0.12500

Inside Rerouting project there is a class `com.here.rerouting.ManeuverIconProvider`

It has the method `loadManeuverIcons()`.

In a comment to that method, there is a piece of information that :

`// Note that you can also find SVG content in the library.`

It is clear how to get .png images, but not about svg.

Please provide information on how to get SVG ones.

Thank you!

**Comment by HERE-SDK-Support-Team** [comment]
Hi @samvmisti, you are using the Android version of this app. It automatically downloads the necessary icons, by default.

However, if you look into the comment, the previous line states that this is the HERE Icon library - at the top of the file you can find the link to the library: 

```
    // The HERE Icon Library provides free-to-use icons for your projects based on the license terms you
    // can find on https://github.com/heremaps/here-icons.
```

Hope this helps.

**Comment by samvmisti** [comment]
@HERE-SDK-Support-Team , thank you!
