### ISSUE TITLE
Flutter SDK: Offline map usage. MapDownloader not found.

### ISSUE THREAD

**Issue by Lazizbek97** [heremaps/here-sdk-examples#278]
I am going to use HERE SDK offline map solution. But when i tried to run and check example offline_maps_app, there as not MapDownloader class and file maploader.dart inside sdk. 
How can i use it? sdk still supports it, or not?
Please give me an example of usage.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @Lazizbek97, if you do not find the MapDownloader class, then you are probably not using the _Navigate Edition_. Using the _Navigate Edition_ will fix this problem. You can download it from [here](https://platform.here.com/portal/sdk). Note that this edition, requires you to contact us to receive valid credentials. More information can be found in the _Developer Guide_ you can find in the downloaded package.
