### ISSUE TITLE
Disposed Navigator

### ISSUE THREAD

**Issue by PanagiotisTsinganos** [heremaps/here-sdk-examples#280]
Occasionally I get the following error in my android app:

> [ERROR] hsdk-navigation - Attempt to use disposed Navigator

I'm using the `Navigator` in tracking mode (i.e. route set to null) and I set the `RoadTextsListener`, `SpeedLimitListener`, and `RoadAttributesListener`.
When this happens none of the listeners is being called. What may cause this issue? The app is set to get location updates in the background.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @PanagiotisTsinganos, please check your code against the implementation of the [BackgroundPositioning](https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/PositioningWithBackgroundUpdates) example app. Without seeing your code it is hard to tell, but when the app is running in background it may happen that the OS shuts down the app for various reasons. In that cases, also the Navigator instance will be disposed. Another reason could be that your own code is disposing the navigator instance. Please leave a comment with more details if this does solve your issue. Thank you!
