### ISSUE TITLE
Generate Here MAP route image with source and destination location marker

### ISSUE THREAD

**Issue by RahulFate** [heremaps/here-sdk-examples#283]
Hi, 

I have to download image using routing API  with source and destination location marker . but in documentation there is no option available for setting marker for generating image. 

 let apiKey = "YOUR_HERE_API_KEY"
   let baseUrl = "https://image.maps.ls.hereapi.com/mia/1.6/routing"
   
   
    // Define the parameters for your routing request
        let routeParameters = [
            "apiKey": apiKey,
            "waypoint0": "lat1,lng1", // Replace with your start coordinates
            "waypoint1": "lat2,lng2", // Replace with your end coordinates
            "lc": "0",
            "lw": "6",
            "t": "0",
            "ppi": "20",
            "w": "800",
            "h": "600"
        ]
        
        
        Please let me know how I can set marker annotation for source and destination location while generating image

**Comment by HERE-SDK-Support-Team** [comment]
Thanks for reaching out to us! This seems to be related to the Routing API and not the HERE SDK.

This repository and its issue tracking are meant for issues with the hosted example apps and this issue does not look like it is related to any example app hosted in this repository.

If you have more questions, please reach out to https://developer.here.com/help - or leave a reply in this thread. Thanks!
