### ISSUE TITLE
Navigation on Android Auto

### ISSUE THREAD

**Issue by spozaaltech** [heremaps/here-sdk-examples#284]
Hi, 

I would like to know if it's possible to add turn-by-turn navigation, showing the routes and maneuvers on Android Auto using Navigation SDK.

Thanks!

**Comment by HERE-SDK-Support-Team** [comment]
Hi @spozaaltech, yes, this is possible. As a starting point you can use this example app: https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/HelloMapAndroidAuto

When the map view is shown, you can manipulate it with the VisualNavigator to run TBT. Hope this helps.
