### ISSUE TITLE
Here Map Marker Click Isssue #504

### ISSUE THREAD

**Issue by Jatinderkanwar** [heremaps/here-sdk-examples#285]
With the Latest sdk release from HERE map we are able to perform click on marker only when we set debuggable true in our App settings. App is working fine in Debug mode as we set debuggable true in this case . When we release apk we cant set debuggable true as it will be a security risk .

mapFragment?.pickMapItems(point2D, 2.0, MapViewBase.PickMapItemsCallback { pickMapItemsResult ->
if (pickMapItemsResult == null) {
return@PickMapItemsCallback
This value is coming as Null always with debuggable false
}
}
Version info : 4.16.1.0.12797-release
debug {
minifyEnabled true
shrinkResources true
zipAlignEnabled true
debuggable false
manifestPlaceholders = [crashlyticsCollectionEnabled: "false"]
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
testCoverageEnabled false
}

**Comment by Jatinderkanwar** [comment]
Hello can you please assist here getting issue while setting debuggable:false  only

**Comment by HERE-SDK-Support-Team** [comment]
@Jatinderkanwar Thanks for reporting this. It may be good to know if this started to happen with 4.16.1 and was working as expected in earlier versions - or not. For release builds, you typically set debuggable to false for security and performance reasons. But it sounds unlikely that this can cause issues. Maybe other settings like minify may have also an effect - plus, for a release build, you may need more code to verify that the callback is always null. This requires some more details.

Can you file a ticket via our help desk: https://developer.here.com/help ? Make sure to provide enough details as listed in this [checklist](https://www.here.com/docs/bundle/sdk-for-android-navigate-developer-guide/page/topics/key-concepts.html#contact-us). 

This repository and its issue tracking are meant for issues with the hosted example apps and this issue does not look like it is related to any example app hosted in this repository. Via help desk you can share your account details and example code, so it will be easier and faster for us to help you. Thanks!

**Comment by Jatinderkanwar** [comment]
Hi Was able to solve issue by applying progurad.rules to classes in which i am using Marker click function. Is this the recommended approach.

**Comment by HERE-SDK-Support-Team** [comment]
@Jatinderkanwar No, this is not really expected. It would be great, if you can contact our support team with more details to get this investigated properly. Thanks.
