### ISSUE TITLE
Missing vehicle restrictions function (Explore Edition)

### ISSUE THREAD

**Issue by WebeyeDev** [heremaps/here-sdk-examples#286]
Hi,

We found a function in the Developer Guide: Vehicle Restrictions. However, this function is missing in the source code.

I would like to ask whether this is a typo in the developer guide, and there is no such function in the Explore Edition, and it won't be there? Or am I mistaken? Perhaps it shouldn't be used this way after all?

**System info:**
HERE SDK for Flutter - Explore Edition 4.16.1

**Help:**
Link what we use: https://www.here.com/docs/bundle/sdk-for-flutter-explore-developer-guide/page/topics/maps.html
![image](https://github.com/heremaps/here-sdk-examples/assets/115453914/7e5dec1d-f9a1-4e0d-81e0-7e58c71d4f3f)

Thanks,

**Comment by WebeyeDev** [comment]
Hi,

It was our mistake. The developer guide confused us, but we found the answer in the feature matrix. This function is available in the Navigate Edition. Sorry.

**Comment by WebeyeDev** [comment]
Hi,

I reopend the issue. The feature matrix is right, but the developer guide isn't.

**Comment by HERE-SDK-Support-Team** [comment]
@WebeyeDev Thanks for the sharp eye! In the developer guide now a big note was added to indicate that not all layers are available for each edition.
