### ISSUE TITLE
Flutter Navigation example

### ISSUE THREAD

**Issue by Matthuffy** [heremaps/here-sdk-examples#29]
Is there a planned turn by turn navigation example planned for flutter?

**Comment by datasun** [comment]
Yes, it is planned, but we cannot clearly say when it will be published here. The code will basically follow the [Android example](https://github.com/heremaps/here-sdk-examples/blob/master/examples/latest/navigate/android/Navigation/app/src/main/java/com/here/navigation/NavigationExample.java), just ported to Dart.

**Comment by Matthuffy** [comment]
Great, looking forward. If you can will be bringing you close to 4k customers. Need to test it out first. will be in touch with your support too soon.

**Comment by datasun** [comment]
Thanks a lot! Our friendly support service should be able to reply quickly.
