### ISSUE TITLE
Getting HERE Places with null coordinates

### ISSUE THREAD

**Issue by TharaaSab** [heremaps/here-sdk-examples#291]
Place object has GeoCoordinates that can be nullable. Can you provide us with an example of such place or a case when to get a place with null geo coordinates?

System info:
HERE SDK Navigate Edition for Android

Thanks and regards,

**Comment by HERE-SDK-Support-Team** [comment]
Hi @TharaaSab, a Place has never null coordinates. It can only null when retrieved from a suggestion's place property. This is mainly for internal reasons. Hope this helps.
