### ISSUE TITLE
[ERROR] sdk-AppContextProvider - SDK NativeEngine doesn't exist during initialisation!

### ISSUE THREAD

**Issue by davidwang5201** [heremaps/here-sdk-examples#293]
I init SDK in application oncreate,
and use in activity,
when first into zhe activity,load map sucess,
when go back and again goto the map actvity,crash
throw
[ERROR] sdk-AppContextProvider - SDK NativeEngine doesn't exist during initialisation!

I has did all mapView life cycle in activity life cycle like:
override fun onPause() {
        mDataBinding.mapView.onPause()
        super.onPause()
    }

 override fun onDestroy() {
        mDataBinding.mapView.onDestroy()
        disposeHERESDK()
        super.onDestroy()
    } 
....

**Comment by HERE-SDK-Support-Team** [comment]
Thanks for reporting! It looks like this may require more input. Can you file a ticket via our help desk: https://developer.here.com/help ? Make sure to provide enough details as listed in this [checklist](https://www.here.com/docs/bundle/sdk-for-android-navigate-developer-guide/page/topics/key-concepts.html#contact-us). This repository and its issue tracking are meant for issues with the hosted example apps and this issue does not look like it is related to any example app hosted in this repository. Via help desk you can share your account details and example code, so it will be easier and faster for us to help you. Thanks!
