### ISSUE TITLE
Unable to find option to download Navigate Edition SDK 

### ISSUE THREAD

**Issue by kapoorshivam** [heremaps/here-sdk-examples#296]
Hi, 
I was exploring various available sdk's for android. So on download SDK [page](https://platform.here.com/portal/sdk) I was able to locate Lite and Explore Edition, but an option to download Navigate Edition SDK is not available
 <img width="319" alt="Screenshot 2024-01-04 at 11 51 39 PM" src="https://github.com/heremaps/here-sdk-examples/assets/16036532/37ce0d77-6493-4d66-8765-c8115bc677ea">

So can anyone please help me how to download Navigate Edition SDK or is there an issue with my billing account/selected plan?

Thanks for the help

**Comment by HERE-SDK-Support-Team** [comment]
Hi @kapoorshivam, sorry for the late reply. We changed access to the _Navigate Edition_ as it requires a special contract and special credentials. Therefore, it is no longer visible, by default, and you can get access to it only after you have made a business inquiry via https://www.here.com/contact. 

Once settled, the _Navigate Edition_ will appear under the link you have shared above. We are sorry for this inconvenience, but we hope you can use the other editions in the meantime. Also, in the future, we plan to make the _Navigate Edition_ more easily accessible. Stay tuned!
