### ISSUE TITLE
Here Map(Navigate framework) version - 4.15.4.0 - App not getting build - following error Undefined symbol: _$sSSs5Error7heresdkMc

### ISSUE THREAD

**Issue by arunlj561** [heremaps/here-sdk-examples#297]
I am getting below error after manually adding the Here Map framework I have followed the instruction mentioned in below link.  
[https://www.here.com/docs/bundle/sdk-for-ios-explore-developer-guide/page/topics/quick-start.html#try-the-example-apps](url). 

Undefined symbols for architecture arm64:
  "_$sSSs5Error7heresdkMc", referenced from:
      _$sS2Ss5Error7heresdkWl in NetworkManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Request for early resolution or guidance.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @arunlj561, sorry for the late reply. The example apps from your link require the _Explore Edition_. Make sure to start with the **HelloMap** example app and follow the steps from the guide. 

When you have unzipped the XCFW, put it into the the app's directory, ie. helloap/heresdk.xcframework

This is enough to build the application.

Please leave a reply, when this does not help and list the exact steps you did (ie. which folder, path, path names, etc). Thank you!
