### ISSUE TITLE
Swift.String : Swift.Error

### ISSUE THREAD

**Issue by kiranmbt** [heremaps/here-sdk-examples#308]
In IOS after import heresdk its showing error like 
Undefined symbol: protocol conformance descriptor for Swift.String : Swift.Error in heresdk.

Please help me for that issue.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @kiranmbt, 

the error message you're seeing typically indicates a linking problem where the Swift compiler is unable to find the necessary metadata for `String` as it conforms to the `Error` protocol. Here are a few steps you can take to troubleshoot and potentially resolve this issue:

1. **Clean and Rebuild:**
   - Start by cleaning your project in Xcode. You can do this by going to **Product > Clean Build Folder**. Sometimes, Xcode can hold onto outdated caches that cause linking errors.
   - After cleaning, rebuild the project to see if the issue persists.

2. **Check Swift Version Compatibility:**
   - Ensure that the version of Swift you are using is compatible with the version used by the HERE SDK. Incompatibilities between Swift versions can sometimes lead to this kind of error. The min iOS version is 13.0. Please list your iOS and Xcode version, if you cannot resolve the issue.

4. **Examine Import Statements:**
   - Ensure that the import statements for the HERE SDK are correct and that there are no missing or duplicate imports that might be causing conflicts.

5. **Linking Flags and Frameworks:**
   - Check your project’s build settings to make sure that all necessary frameworks are linked properly and that there are no missing or incorrect compiler flags.
   - Go to **Target > Build Phases > Link Binary with Libraries** to verify this.

6. **Xcode and Swift Toolchain:**
   - If you recently upgraded Xcode or the Swift toolchain, make sure everything is configured correctly. Sometimes, upgrading can change paths or settings that were previously in place.
   - Consider downloading an additional Swift toolchain if compatibility issues are suspected.

If this does not help, please list your environment (Xcode version, Swift version, iOS SDK version), and how you integrated the HERE SDK into your project. Thank you!

**Comment by kiranmbt** [comment]
We have tried mentioned all the points. but still issue not resolved.
IOS Version - 15.0
Xcode Version - 15.3
IOS SDK Version - heresdk-explore-ios-4.18.0.0.101086

Thanks in advance.

**Comment by HERE-SDK-Support-Team** [comment]
@kiranmbt What is the MacOS version you are using? Thanks.

**Comment by HERE-SDK-Support-Team** [comment]
Closing since there was no further update. Please leave a comment if there is an update. Thanks!
