### ISSUE TITLE
Map label language change

### ISSUE THREAD

**Issue by maheshsystimanx** [heremaps/here-sdk-examples#31]
How to change map label language hindi to english

**Comment by datasun** [comment]
You can set the `primaryLanguage` for the `HereMapController` (= Flutter) or MapView (native SDKs). Hope this helps. If not, please leave a comment. Thanks!

**Comment by nicks258** [comment]
There is no available method as primary language can you please post some sample code for flutter. Thanks

**Comment by HERE-SDK-Support-Team** [comment]
Hi @WebeyeDev, sure here is example code:

`HereMapController.primaryLanguage = HERE.LanguageCode.hiIn; `

**Comment by WebeyeDev** [comment]
It works for as. Thanks.

**Comment by Appu-Venky** [comment]
how  to  only  india showing national language hindi how to change to english

**Comment by Appu-Venky** [comment]
iam using above  code but  that chnage the language entaire the map  but i need only indial natinal langage hindi  to english how to chnage

**Comment by ipawanshukla** [comment]
@Appu-Venky we are unable to understand your exact issue.. Do you want to set the Map Language to Hindi or English? Here's how you can update the language - https://www.here.com/docs/bundle/sdk-for-flutter-navigate-developer-guide/page/topics/maps.html#set-a-map-language and here' s the coverage information -  https://www.here.com/docs/bundle/sdk-for-flutter-navigate-developer-guide/page/topics/coverage-information.html
