### ISSUE TITLE
Different line layout

### ISSUE THREAD

**Issue by pedroicandido** [heremaps/here-sdk-examples#312]
Hey guys, how are you doing? I have a question about your SDK and would appreciate your help. I'll try to explain my issue starting with the type of service my company provides. We are a public transportation company, meaning other companies hire us to pick up their employees at certain bus stops. To make this happen, we have a team that studies the best route and possible stops for each line of each company, lines that are also generated by the HERE engine. The issue lies in the part of the app used by our drivers. In this app, the driver can see the route they should take based on the latitude and longitude sent from the routes generated by the website. However, when this route is calculated in the app (using your SDK), sometimes the routes are different. What I would like to know is if it's possible to generate these routes exactly the same, because as they are bus routes and fixed, they shouldn't change.
The first image is the route generated by our website and how it should appear in the app.
<img width="1053" alt="git-example-1" src="https://github.com/heremaps/here-sdk-examples/assets/49328524/20785781-35bc-4ff4-8671-0b190f83eddc">

This second image is when the app calculates the route within the application.
<img width="322" alt="git-example-2" src="https://github.com/heremaps/here-sdk-examples/assets/49328524/f8e7e561-b2ab-4214-af66-0eb865f21cd2">

**Comment by HERE-SDK-Support-Team** [comment]
Hi @pedroicandido, thank you very much for the question. For existing customers it is best if you contact our friendly support team via https://www.here.com/contact - they will be happy to help! Please also send the exact parameters and coordinates, so we can replicate the scenario. 

In general, you have several options to solve your problem. 

- You can use **TrafficOptimizationMode** and disable it to avoid that the route will depend on the current traffic situation.
- Or you use the **OfflineRoutingEngine**, then you will also ignore any traffic.
- Use multiple waypoints to shape the route. For your case, **stopover** waypoints sound like the best option.
- If you know already the exact route, you can use the **importRoute()** feature and pass in the coordinates. 
- You can also combine all the above options.
