### ISSUE TITLE
Custom Map marker Layering

### ISSUE THREAD

**Issue by RissiePit** [heremaps/here-sdk-examples#313]
Does the flutter Here SDK support a map marker "layering"?
I need to show a map marker including travel direction, or in another case combining two images to create single map marker.

![Screenshot 2024-05-06 at 10 14 31](https://github.com/heremaps/here-sdk-examples/assets/4973279/51ea0842-9786-48ba-b514-6261c4de3954)

Any assistance will be appreciated.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @RissiePit,

thank you for your question. This should work, you can stack multiple map markers upon each other and transparent images are supported, too. Alternatively, you can use `MapViewPins` which can be composed out of multiple native views. However, for map marker, the `MapMarker` class is better suited.  Hope this helps!
