### ISSUE TITLE
Change marker

### ISSUE THREAD

**Issue by MauroGentile** [heremaps/here-sdk-examples#314]
I want to use the visualNavigator and be able to switch from tracking mode to navigation mode. My understanding is that this is achieved by switching visualNavigator.route to null (tracking) to a specific route (navigation). 

When switching, I also want to switch the Location indicator. To do so I do the following:
in init, I create a LocatioIndicator like this
```
_locationIndicator = LocationIndicator();
_locationIndicator.isAccuracyVisualized = true;
_locationIndicator.locationIndicatorStyle = LocationIndicatorIndicatorStyle.pedestrian;
_locationIndicator.enable(hereMapController);
visualNavigator.customLocationIndicator = _locationIndicator;
```
When I want to switch to navigation:

```
_locationIndicator.locationIndicatorStyle = LocationIndicatorIndicatorStyle.navigation;
visualNavigator.customLocationIndicator = _locationIndicator;
```

When I want to go back to pedestrian, I call the following:

```
_locationIndicator.locationIndicatorStyle = LocationIndicatorIndicatorStyle.pedestrian;
visualNavigator.customLocationIndicator = _locationIndicator;
```
However the above seems not to have effect.... I always see the default indicator being displayed which, I understand, should automatically be disabled by assigning a no null LocationIndicator instance to visualNavigator.customLocationIndicator
Is there anything I am doing wrong?

**Comment by HERE-SDK-Support-Team** [comment]
Hi @MauroGentile, in general, this assumption is correct. You can see an example of how to switch the `LocationIndicator` during guidance [here](https://github.com/heremaps/here-sdk-examples/blob/54ac3113991f39e295a373cc6d110c9627128559/examples/latest/navigate/flutter/navigation_custom/lib/main.dart#L239).

However,  note that the type of the `LocationIndicator` is taken from the route's `TransportMode`. It cannot be overriden during guidance. During tracking mode you can specify the marker type via:

` _visualNavigator!.trackingTransportMode = TransportMode.pedestrian; `
 
 Hope this helps! Please leave a reply when you have more questions. Thanks!
