### ISSUE TITLE
[Android - Explore Edition] The map blink and throwing error

### ISSUE THREAD

**Issue by ysavr** [heremaps/here-sdk-examples#315]
here map sdk: heresdk-explore-android-4.18.0.0.101086

when user stay longer on application and doing nothing, maps blink and throwing error,

`[ERROR] hsdk-harp-sdk - Invalid target map in removeLayer`

**Comment by HERE-SDK-Support-Team** [comment]
Hi @ysavr, 

thanks for reporting. Can you try to use the latest HERE SDK release and see if this fixes your issue? There have been recent changes around the map view. If the issue persists, please leave a reply with more details: I.e. which example app did you execute - plus, please take a look at this [bug reporting template](https://www.here.com/docs/bundle/sdk-for-android-navigate-developer-guide/page/topics/key-concepts.html#contact-us). Thanks!
