### ISSUE TITLE
Initialization of HERE SDK failed: FAILED_TO_CREATE_ANALYTICS_SERVICE

### ISSUE THREAD

**Issue by Strikelon** [heremaps/here-sdk-examples#322]
We use android-sdk-navigate/4.12.11.0

And in firebase crashlitics we got some float crashes on this devices:

Xiaomi Redmi Note 13, Android 14

Samsung Galaxy S21 5G, Android 13,

The error is "java.lang.RuntimeException - Initialization of HERE SDK failed: FAILED_TO_CREATE_ANALYTICS_SERVICE"

In this method:

    private fun initializeHereSDK() {
        val options = SDKOptions(HERE_ACCESS_KEY_ID, HERE_ACCESS_KEY_SECRET)
        try {
            SDKNativeEngine.makeSharedInstance(context, options)
        } catch (e: InstantiationErrorException) {
            throw RuntimeException("Initialization of HERE SDK failed: " + e.error.name)
        }
    }

1) why might this "FAILED_TO_CREATE_ANALYTICS_SERVICE" happen?
2) what is the best way to handle this error? maybe try to initialize it again in a loop with a slight delay?

**Comment by HERE-SDK-Support-Team** [comment]
Hi @Strikelon,

this issues has been fixed. Can you try 4.19.5. or newer? If the issue persist, please leave a reply or contact us directly via: https://www.here.com/docs/bundle/sdk-for-android-navigate-developer-guide/page/topics/tips-troubleshooting.html

Hope this helps. Thanks.
