### ISSUE TITLE
Android, Navigate Edition: Traffic incidents on route

### ISSUE THREAD

**Issue by SergeHelfrichPI** [heremaps/here-sdk-examples#324]
We use the Navigate SDK for Android, version 4.18.5.0.

We want to notify the user about traffic incidents on the route and display them on the map. 

First we call Section.getTrafficIncidents() to retrieve a list of incidents. 'TrafficIncidentOnRoute' provides some properties of the incident, but not its location.

To resolve the location we try to match the incident by ID with the incidents retrieved from the 'TrafficEngine'. Unfortunaly we can only query within a rather tiny radius (or box, or corridor) or an error will occur: 'TrafficQueryError: INVALID_GEOMETRY'.

How should we proceed to obtain the incidents and their locations on a route longer than a couple of kilometers?

**Comment by HERE-SDK-Support-Team** [comment]
Hi @SergeHelfrichPI ,

when searching for the ID, you should be able to do so without specifying a box or a corrdior. 

```
    private void findIncidentByID(String originalId) {
        TrafficIncidentLookupOptions trafficIncidentsQueryOptions = new TrafficIncidentLookupOptions();
        // Optionally, specify a language:
        // the language of the country where the incident occurs is used.
        // trafficIncidentsQueryOptions.languageCode = LanguageCode.EN_US;
        trafficEngine.lookupIncident(originalId, trafficIncidentsQueryOptions, new TrafficIncidentLookupCallback() {
            @Override
            public void onTrafficIncidentFetched(@Nullable TrafficQueryError trafficQueryError, @Nullable TrafficIncident trafficIncident) {
                if (trafficQueryError == null) {
                    Log.d(TAG, "Fetched TrafficIncident from lookup request." +
                            " Description: " + trafficIncident.getDescription().text);
                    addTrafficIncidentsMapPolyline(trafficIncident.getLocation().polyline);
                } else {
                    showDialog("TrafficLookupError:", trafficQueryError.toString());
                }
            }
        });
    }
`

This is also shown in the **Traffic** example app. 

Hope this helps. Thanks!
