### ISSUE TITLE
offscreen map using backend technology stack

### ISSUE THREAD

**Issue by jainricha** [heremaps/here-sdk-examples#326]
Hello,

Is it feasible to generate offscreen map object and the snapshot of the same via any backend technology stack?

Please suggest.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @jainricha,

no, this looks like rather a task for the app-side. See this example app which does create offscreen images from the map, without actually showing the map: https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/OffscreenMapSurface

Hope this helps. Thanks!
