### ISSUE TITLE
Failed to read here/nokia map version.

### ISSUE THREAD

**Issue by AzimST** [heremaps/here-sdk-examples#328]
When using here maps that I want to use in my qt application, I get this error and the screen does not come up. how can i solve it
![image](https://github.com/user-attachments/assets/cc77d732-7565-4f60-b3a8-dab6a19ff78f)
![image](https://github.com/user-attachments/assets/bd5413bf-7399-4f2d-a0bf-55e508d8f5d6)
My QML Code
`
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Window 2.15
// Here Maps import
import QtLocation 5.15
import QtPositioning 5.15

Window {
    visible: true
    width: 640
    height: 480
    title: qsTr("Here Maps Example")

    Plugin {
        id: hereMaps
        name: "here"

        // Your HERE API key

        PluginParameter {
            name: "here.app_id"
            value: "e*******************U"
        }

        PluginParameter {
            name: "here.token"
            value: "K***********************w"
        }
    }

    Map {
        anchors.fill: parent
        plugin: hereMaps
        center: QtPositioning.coordinate(38.4501, 27.1777)
        zoomLevel: 14
    }
}
`

My errors
```
QML debugging is enabled. Only use this in a safe environment.
No proxy parameter specified.
Failed to read here/nokia map version.
	QGeoTileRequestManager: Failed to fetch tile (9430,6293,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9430,6292,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9429,6292,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9427,6293,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9429,6293,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9428,6292,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9429,6294,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9427,6294,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9430,6294,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9428,6293,14) 5 times, giving up. Last error message was: 'Host requires authentication'
QGeoTileRequestManager: Failed to fetch tile (9427,6292,14) 5 times, giving up. Last error message was: 'Host requires authentication'

```

**Comment by HERE-SDK-Support-Team** [comment]
Hi @AzimST 

unfortunately, we cannot help with Qt questions. This is not directly supported by the HERE SDK. You can try to reach out to our in-house support team: https://www.here.com/contact?intref=dev_docum

Hope this helps. Thanks.
