### ISSUE TITLE
Interactive Map Layer in Flutter

### ISSUE THREAD

**Issue by devsideal** [heremaps/here-sdk-examples#329]
Does HERE SDK for Flutter ([Explore Edition](https://github.com/heremaps/here-sdk-examples/blob/master/examples/latest/explore/flutter), [Navigate Edition](https://github.com/heremaps/here-sdk-examples/blob/master/examples/latest/navigate/flutter)) supports Intractive Map Layer feature, 

I Searched but did not found any way to show interactive map layer by layer id in flutter.
Is there any example for flutter like this:
https://developer.here.com/documentation/examples/maps-js/data/transit-imlA

**Comment by HERE-SDK-Support-Team** [comment]
Closing, since there was no more activity. Please leave a comment when you have new information. Thanks!
