### ISSUE TITLE
Android: Black Screen on back button

### ISSUE THREAD

**Issue by LazarRistic** [heremaps/here-sdk-examples#33]
Hi, i discoverd when you want to come back to Activity who has here map on it, map turns black. Tested on (Samsung Galaxy S7 edge SM-G935F, Samsung Galaxy Note 10 SM-N970F, Huawei LUA-L21, HUAWEI Honor 8 Lite PRA-LX1)

You can check my code on forked `here-sdk-examples`, i just added button for starting new activity.

https://github.com/LazarRistic/here-sdk-examples/tree/master/examples/latest/lite/android/MapObjectsLite

Any ides?

Thank you in advance.

**Comment by datasun** [comment]
See answer for https://github.com/heremaps/here-sdk-examples/issues/26 

The _Lite Edition_ supports only one instance of a map view. If you want to show a 2nd instance on a new screen, the previous instance must be destroyed. With the next release the HERE SDK will detect two instance by throwing an exception.

If this is not the issue you saw, please comment. Thanks!
