### ISSUE TITLE
Request to add comment for the Tile Key that is using the TMC spec

### ISSUE THREAD

**Issue by ling-jiang-here** [heremaps/here-sdk-examples#334]
This is the feedback from the support case CS0134590 that they want to add a comment to the following line saying that the Tile Key in this project is using the TMC spec:
https://github.com/heremaps/here-sdk-examples/blob/5ef88aacface87c644ea29ab07a8685d65f46146/examples/latest/navigate/android/CustomRasterTileSource/app/src/main/java/com/here/sdk/customrastertilesource/LocalRasterTileSource.java#L70

There are several specs as stated in the following online article, while HERE is using the TMC spec:
https://gis.stackexchange.com/questions/132242/what-are-the-differences-between-tms-xyz-wmts

**Comment by HERE-SDK-Support-Team** [comment]
This has been already handled internally via CS0134590.

Thanks.
