### ISSUE TITLE
Flutter navigation edition turns are very quick how to make it smooth

### ISSUE THREAD

**Issue by mohanve7** [heremaps/here-sdk-examples#336]

**Comment by HERE-SDK-Support-Team** [comment]
Hi @mohanve7, this looks like a question for our support team as it touches the HERE SDK behavior directly and not the example apps:

https://www.here.com/contact?intref=dev_docum

We assume you refer to the avoid U-Turns option. We might more details, logs and routes to see where this happens. In general, such behavior is under constant improvement for each release and turns depend also a lot on choosing the right route options including car or truck specifications such as weight and dimensions.

Hope this helps.
