### ISSUE TITLE
How to add functionality like 3d map view and compass like in here maps app using flutter sdk

### ISSUE THREAD

**Issue by mohanve7** [heremaps/here-sdk-examples#337]
[]
![Screenshot_20240822_164902](https://github.com/user-attachments/assets/f2022c75-60fc-462f-b14b-fc8bae63e253)

**Comment by HERE-SDK-Support-Team** [comment]
Hi @mohanve7,

at the moment, there is no convenience UI element for this, so you have to implement this on app side. 
You need to access the device's sensor data to implement a compass orientation.
With the `MapCamera` you can control how to rotate the map view, how to tilt it and so on.

We might implement a convenient API for this in the future, but for now this is not in sight. Hope this helps.
