### ISSUE TITLE
Geocoordinates of the center of the screen in the visualNavigator

### ISSUE THREAD

**Issue by MauroGentile** [heremaps/here-sdk-examples#339]
From visualNavigator, is it possible to know the geocoordinates of the point in the center of the screen?

If I use 

`
hereMapController.camera.state.targetCoordinates 
`

when visualNavigator on, sometimes I get a point that is vertically shifted wrt the point in the center of the screen.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @MauroGentile,

The VisualNavigator controls the principal point. Get the CameraBehavior and from there access the normalized principal point. By default, this is shifted vertically. 

However, if you have not changed this, the point should not change. And you are correct, the targetCoordinates should always indicate that location. 

Can you share how you are accessing the targetCoordinates? And how do you verify, that the coords are vertically shifted? Is this visible in the app? Thanks.

**Comment by HERE-SDK-Support-Team** [comment]
Closing for now. Please leave a comment if the above hints do not help to narrow down the problem. Thank you!
