### ISSUE TITLE
Hot reload don't word in android studio 3.6

### ISSUE THREAD

**Issue by phucho236** [heremaps/here-sdk-examples#34]
![image](https://user-images.githubusercontent.com/54463698/86505892-2940bd80-bdf4-11ea-80ac-7d1ed63de30b.png)

Hi team.
SdkContext.init(IsolateOrigin.main) Make the hot reload feature not work in android studio 3.6, but working normally in vscode.
i'm try convert the code snippet to initState() 
![image](https://user-images.githubusercontent.com/54463698/86506048-ab7db180-bdf5-11ea-9ebe-a2224517033d.png)
and noww this don't work... solution to this problem ?

**Comment by datasun** [comment]
Thanks for your comment. The hot reload bug is a known issue, it is fixed with the new release for the HERE SDK for Flutter, version 4.4.0.2. - it will be released today.
