### ISSUE TITLE
getDownloadableRegionsWithLanguageCode in offline_maps_app gets stuck 

### ISSUE THREAD

**Issue by MauroGentile** [heremaps/here-sdk-examples#341]
I am running your offline_maps_app and quite often the call to getDownloadableRegionsWithLanguageCode does not produce any output.

Sometimes I can see a pop up window informing that 6 continents have been found, but most of the times, nothing is shown.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @MauroGentile, thanks for reporting. We'll try to reproduce. 

Meanwhile, do you have any logs? The method shows a dialogue in case of an error, other. It will also produce logs. This might help to narrow this down. For now, we suspect, that the dialogue might just be blocked by another one. 

Thanks.

**Comment by MauroGentile** [comment]
@HERE-SDK-Support-Team Sorry for the delay of my answer. I must say that I have not experienced the problem any longer since I open this issue. I would therefore close the issue and reopen it only if the problem pops up again.
Thanks for helping
