### ISSUE TITLE
HikingDiary example lacks persistence of recorded GPX files when application is restarted without cache

### ISSUE THREAD

**Issue by MVHINC** [heremaps/here-sdk-examples#343]
Hi.
https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/ios/HikingDiary
Using the app above the entries are kept only for the current session.
Restart the app and they will be lost, regardless of the OS.

**Comment by HERE-SDK-Support-Team** [comment]
Hi @MVHINC, yes, this is a confirmed regression on app-side. The functionaility to store the entries is not releated to the HERE SDK and we will fix the example app within the next two weeks. Stay tuned and sorry for the inconvenience. Thanks.
