### ISSUE TITLE
Android App Crashes

### ISSUE THREAD

**Issue by matice2** [heremaps/here-sdk-examples#344]
Hi,

we use the Navigate Edition and the App crashes quite often on Android with a not informative error log unfortunately. This is from Firebase Crashlytics: 

`          Crashed: Thread: SIGABRT  0x0000000000000000
#00 pc 0x22988 libc.so (BuildId: 3326eee918b5ef1dbb5d558ca672e8e5)
#01 pc 0x2295c libc.so (BuildId: 3326eee918b5ef1dbb5d558ca672e8e5)
#02 pc 0x4538a8 libart.so (BuildId: d40c91738e18f7a89c15633e1f502ac6)
#03 pc 0x8d20 libbase.so (BuildId: 366e5f02affb29a6ea789d0516fcf36a)
#04 pc 0x30b55c libart.so (BuildId: d40c91738e18f7a89c15633e1f502ac6)
#05 pc 0x1af1a18 libheresdk.so (Java_com_here_sdk_core_Metadata_cacheThisInstance) (BuildId: da89a7bafc71673699a2dadb9b7b081b3c305cbf)
#06 pc 0x18d2da4 libheresdk.so (Java_com_here_sdk_routing_CalculateRouteCallbackImpl_disposeNativeHandle) (BuildId: da89a7bafc71673699a2dadb9b7b081b3c305cbf)
#07 pc 0x1f3fb6c libheresdk.so (here_sdk_sdk_venue_threading_VenueThreads_get_type_id) (BuildId: da89a7bafc71673699a2dadb9b7b081b3c305cbf)
#08 pc 0x1f819f8 libheresdk.so (here_sdk_sdk_venue_threading_VenueThreads_get_type_id) (BuildId: da89a7bafc71673699a2dadb9b7b081b3c305cbf)
#09 pc 0x1656acc libheresdk.so (Java_com_here_sdk_core_threading_RunnableImpl_run) (BuildId: da89a7bafc71673699a2dadb9b7b081b3c305cbf)
        `

We have not found reproducible steps yet. Can you help us with that?

Thanks!

**Comment by HERE-SDK-Support-Team** [comment]
Hi @matice2, thanks for reporting. The crash needs to be symbolicated. Please reach out to us, following the steps listed here: https://www.here.com/docs/bundle/sdk-for-android-navigate-developer-guide/page/topics/tips-support.html#getting-help-when-bugs-occur - thank you!
