### ISSUE TITLE
flutter navigation edition how to adjust tilt while using DynamicCameraBehavior

### ISSUE THREAD

**Issue by mohanve7** [heremaps/here-sdk-examples#345]
I was currently using DynamicCameraBehavior which auto adjust camera angles, i want to customize tilt angle when camera zooms in, how can i achieve this?

**Comment by HERE-SDK-Support-Team** [comment]
Hi @mohanve7, for any custom camera behavior it is possible to use the `FixedCameraBehavior` and update the values for tilt and zoom manually. 

At the moment, there is no other option to customize how `DynamicCameraBehavior` will behave, except for adjusting the principal point. 

Hope this helps!
