### ISSUE TITLE
file locale.dart that does not exist

### ISSUE THREAD

**Issue by phucho236** [heremaps/here-sdk-examples#37]
Hello team !.
![image](https://user-images.githubusercontent.com/54463698/86725193-a453df00-c053-11ea-8adc-6d14949c0443.png)
i'm try pubget in plugins and flutter clean but still not different.how do i can find a file   ?

**Comment by datasun** [comment]
`flutter pub get` should get the package, based on pubspec.yaml. Can you confirm that this is executed? 
Also, please make sure that `pubspec.yaml` is not modified when you try one of the examples for the 1st time. Let us know if this does not help and provide some more results like running the Flutter doctor. Thanks.

**Comment by phucho236** [comment]
![image](https://user-images.githubusercontent.com/54463698/86753972-b42aed80-c06a-11ea-8e14-e3f626e24013.png)
just restart the project. Here is how to solve the problem. and now i have new problem. pubspec.lock in project get intl old version: 0.15.8.  how i can get version: "0.16.1"

**Comment by phucho236** [comment]
package flutter_money_formatter used intl version 0.15.8,This is the cause for Here Sdk don't get intl new version
... sory my english.
