### ISSUE TITLE
MapImage cause crack App

### ISSUE THREAD

**Issue by phucho236** [heremaps/here-sdk-examples#38]
![image](https://user-images.githubusercontent.com/54463698/87389042-29993f80-c5d0-11ea-979b-7c5a0323e35f.png)
MapImages only work with ".withPixelDataAndImageFormat" ,i'm using Images in my database 
to create Mapmaker object, but my Images object is so big that i want to minify it

**Comment by datasun** [comment]
For the HERE SDK for Flutter, the method you are calling is only supporting SVG Tiny, see here: https://docs.in.here.com/static/41122/435365/html/mapview/MapImage/MapImage.withImageDataImageFormatWidthAndHeight.html

So, the method cannot be used to scale a PNG image.
