### ISSUE TITLE
[Android] Starter/Premium getZoom/setZoom equivalent in Lite/Explore

### ISSUE THREAD

**Issue by axionnneeeel** [heremaps/here-sdk-examples#39]
Hello,

I can't find the equivalent method for getZoom and setZoom(Starter/Premium) in Lite/Explore edition.

Can please someone help me with that ?

**Comment by datasun** [comment]
For Lite simply call `mapView.camera.setZoomLevel(14)`.
For Explore & Navigate, for examples: `camera.lookAt(point: GeoCoordinates(latitude: 52.530932, longitude: 13.384915), distanceInMeters: 1000 * 2)`.

**Comment by axionnneeeel** [comment]
Hello, thanks for your reply.

1. lookAt seems equivalent to zoomTo, more than setZoomLevel, am I wrong ? 
2. How about the getZoom() function equivalent? How can you get the zoom level in explore ?

**Comment by datasun** [comment]
Yes, correct, there are several overloads of the lookAt() method available with different paramters. The main difference is that Explore is more accurate by defining the distance in meters - whereas the zoom levels in Lite are a bit artificial (ie. you don't know exactly how far the camera is from earth, until you measure it).

You can get the current distance from the Camera's state (equivalent of getZoom()). Let me know if this does not answer your question. Thanks!

**Comment by axionnneeeel** [comment]
But is there a equivalent between zoom level as int ( 14 in you example ) and distance in metters ( 1000 * 2 in your example ) ?

**Comment by datasun** [comment]
Yes, there is, but we do not provide a conversion table. Zoom level 14 is equal to a certain distance to earth (in meters). The exact value one needs to find out true comparison.
