### ISSUE TITLE
FontFace and Font Issues with FLutter on Android - Maps 

### ISSUE THREAD

**Issue by Beautylivery** [heremaps/here-sdk-examples#45]
Hi,

I run into an issue with Android Phones while using Flutter (in General)
E/magma-text-agg(25048): [ERROR] magma-text-agg - Could not find font: 'fonts/NotoSansKhmer-Regular-unhinted.ttf'

An another Error using Here Maps in China Area
E/CL_magma(25048): [ERROR] CL_magma - Can't find FontFace for charcode: 4135

I am using here maps 4.4.2.0

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale de-DE)
    • Flutter version 1.17.5 at /Users/-/development/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/-/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/-/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Redmi Note 8 • 18d3ce30 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by datasun** [comment]
Thanks for reporting. We might need to have some more information on how to reproduce this. And: What exactly is the issue you are seeing (or is this an error log without impact)? Plus: Which example app have you executed and was there any modification done on your side? Is this happening only for a specific map area?

**Comment by Beautylivery** [comment]
Hi I was using the Hello Map Package.
It basically directly appears after i started the Debug mode on a real Android Device from Xiaomi Redmi Note 8running Miui 11 powered by Android . 
I can use the Function and its not stopping the app or throwing an Error. I believe you embedded it in a catch with Print the Error. 

It appears directly after booting up the function and is relatively often appearing while moving through the Map of Berlin in my case.

Second Error appears when i zoom out of Germany and move to China and zoom into beijing.... here the error becomes more severe as its seems not to display many of the names in the Chinese Cities or streets because of the missing Character set i assume .

On my side i was not doing any modifification i am aware of, i was later using it in one of my other App projects and had the same issues on the same phone.

**Comment by datasun** [comment]
Ok, thanks, we will look into this!

**Comment by datasun** [comment]
It seems we added these missing fonts already with **release 4.4.3**. This release is available only to selected customers. The next public release will be 4.4.0, so I would suggest to re-test with one of the next versions of the HERE SDK and the issue should be gone. If not, please comment! You can contact our service team and ask for access to 4.4.3. ... Hope this will help.

**Comment by HBHXTRA** [comment]
Can someone help me getting access to the navigation SDK and access keys to be able to use it ?
I’m going to through sales pain... at the moment we just want to check if we can move forward with Here
We’ll just end up dropping here... no way to use the navigation SDK.....

If this works, well anyway go through sales to hammer an agreement or something but at the moment we’re blocked even at the beginning... also any guidance on when we go out of beta ?

**Comment by leopectus** [comment]
Hi @HBHXTRA, I can help you get in contact with sales. The easiest option is to go to the developer portal and use the contact us form (linked at the bottom of the front page). If you're having trouble with that, you can also reach out to me. For example, you can DM me on twitter @sueselbeck). Or find me on LinkedIn.

**Comment by HBHXTRA** [comment]
Thanks @leopectus I just sent you an invite via LinkedIn to connect and be able to have a short chat.

We just feel it's premature to spend time and energy talking to Sales. We want to spend our time and energy developing a prototype then an MVP and see if Here SDK is the right technology to use for us which seems to be the case. This is why we would like to access the Navigation SDK and be able to use it.
