### ISSUE TITLE
Flutter - How to update Here map marker in flutter?

### ISSUE THREAD

**Issue by MungaraJay** [heremaps/here-sdk-examples#50]
```
Hello,

I am using following code to set my marker in Here Maps. Now, I want to update the position of the marker in the app from the GeoCoordinates(13.6211, 123.1903) to GeoCoordinates(15.6211, 125.1903) when pressing on a button.

But, I am confused and I didn't find a way to update the marker in the map.

import 'package:flutter/material.dart';
import 'package:here_sdk/core.dart';
import 'package:here_sdk/mapview.dart';

void main() {
  SdkContext.init(IsolateOrigin.main);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'HERE SDK for Flutter - Hello Map!',
      home: HereMap(onMapCreated: _onMapCreated),
    );
  }

  void _onMapCreated(HereMapController hereMapController) {
     var image = new MapImage.withFilePathAndWidthAndHeight(
        '<?xml version="1.0" standalone="no"?>' +
            '<svg width="4cm" height="4cm" viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg" version="1.1">' +
            '<path d="M 100 100 L 300 100 L 200 300 z"M fill="red" stroke="blue" stroke-width="3" />' +
            '</svg>',
        100,
        100);
    var mapmarker = new MapMarker(GeoCoordinates(13.6211, 123.1903), image);
    hereMapController.mapScene.addMapMarker(mapmarker);
    hereMapController.mapScene.loadSceneForMapScheme(MapScheme.normalNight,
        (MapError error) {
      if (error != null) {
        print("Map scene not loaded. MapError: " + error.toString());
      }
      debugPrint('hi im dino');
      hereMapController.camera
          .lookAtPointWithDistance(GeoCoordinates(13.6211, 123.1903), 1000.0);
      hereMapController.release();
    });

    hereMapController.release();
  }
}
```

Can you please provide a solution?

Thanks.

**Comment by datasun** [comment]
Hello Jay, yes, that's possible, you can update the marker by [setting new coordinates](https://developer.here.com/documentation/flutter-sdk-navigate/4.5.0.0/api_reference/mapview/MapMarker/coordinates.html). 

This way, a marker that is already drawn on the map, will be instantly updated to the new location. You can set / get the current coordinates on the `MapMarker` instance with:

```
set coordinates(GeoCoordinates value);
GeoCoordinates get coordinates;
```

**Comment by vikasChhipi2000** [comment]
is there a way for clustering the marker in here map for flutter application

**Comment by imnitink** [comment]
> is there a way for clustering the marker in here map for flutter application

Hello Vikas,
Did you find a way to do clustering in here maps?

**Comment by datasun** [comment]
@imnitink, @vikasChhipi2000, marker clustering is a planned feature, but it is not yet supported on SDK side. Until then, only app-side solutions are possible.

**Comment by imnitink** [comment]
@datasun can you please help me with any app side solution?

**Comment by datasun** [comment]
@imnitink Not with a full working example, but I would start by changing the visibility of markers based on their location and camera distance. For example, markers that are close to each other can be made invisible for higher zoom levels and replaced by a central one. There are a lot of different possible ways to deal with it UI-wise, so it's hard to give a general advice.
