### ISSUE TITLE
SavedInstanceState value is getting null. When launching an app its crashing.

### ISSUE THREAD

**Issue by arunarajput** [heremaps/here-sdk-examples#52]
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;

import com.here.sdk.core.GeoCoordinates;
import com.here.sdk.mapview.MapError;
import com.here.sdk.mapview.MapScene;
import com.here.sdk.mapview.MapScheme;
import com.here.sdk.mapview.MapView;

public class MainActivity extends AppCompatActivity {

    private MapView mapView;
    private PermissionsRequestor permissionsRequestor;

    @Override

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mapView = findViewById(R.id.map_view);
        this.mapView = new MapView(this);
        mapView.onCreate(savedInstanceState);

        mapView.setOnReadyListener(new MapView.OnReadyListener() {
            @Override
            public void onMapViewReady() {
                Log.d("TAG", "HERE Rendering Engine attached.");
            }
        });
        handleAndroidPermissions();
    }

    private void handleAndroidPermissions() {
        permissionsRequestor = new PermissionsRequestor(this);
        permissionsRequestor.request(new PermissionsRequestor.ResultListener(){
            @Override
            public void permissionsGranted() {
                loadMapScene();
            }

            @Override

            public void permissionsDenied() {

                Log.e("TAG", "Permissions denied by user.");
            }
        });
    }

    @Override

    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        permissionsRequestor.onRequestPermissionsResult(requestCode, grantResults);
    }

    private void loadMapScene() {
        mapView.getMapScene().loadScene(MapScheme.NORMAL_DAY, new MapScene.LoadSceneCallback() {
            @Override
            public void onLoadScene(@Nullable MapError mapError) {

                if (mapError == null) {
                    double distanceInMeters = 1000 * 10;
                    mapView.getCamera().lookAt(
                            new GeoCoordinates(52.530932, 13.384915), distanceInMeters);
                } else {
                    Log.d("TAG", "Loading map failed: mapError: " + mapError.name());
                }
            }
        });
    }

    @Override
    protected void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }
}](url)

**Comment by datasun** [comment]
Hi there, can you provide some more details? Your code snippet is the **HelloMap** example, except that you add this line in `onCreate()`:

`this.mapView = new MapView(this);`

This looks wrong: You already set the `mapView` instance from layout in the line above. Can you try the non-modified example app first and see if that works for you? 

PS: `savedInstanceState` is coming from Android itself. The `Bundle` parameter in `onCreate()` is `Nullable`, so this cannot crash.

**Comment by datasun** [comment]
Closing. If this did not fix your issue, please comment. Thanks!

**Comment by arunarajput** [comment]
Example app(Hello Map) is not working for me. its getting crash.

**Comment by datasun** [comment]
Hi, ok, but then please provide more details. We need to see the crash log. Platform, device. 
Are you sure you have used the unmodified example? Because the code you pasted above is not original code from us.
Happy to help, when we get more details. Thanks.

**Comment by arunarajput** [comment]
Hi,,,I run on emulator (pixel 2 API 29) and getting crash...I have used only same example code didn't change anything in the code...
Below is logcat values:
.2020-10-16 12:55:22.755 8117-8194/? A/CL_magma: [FATAL] CL_magma - Couldn't load the default shader.
2020-10-16 12:55:22.755 8117-8194/? A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 8194 (Thread-44), pid 8117 (.here.mapmarker)

**Comment by datasun** [comment]
Thanks! This is happening because the HERE SDK requires OPENGL ES 3.0. You try to run on a _real device_ instead, or change the configuration of your emulator to ensure it uses Open GL ES 3.0. Open GL 2.0 will not work. 

PS: We know that the error message is not very precise and we hope we can improve it in the future.
