### ISSUE TITLE
Hiding POI Icons on Flutter

### ISSUE THREAD

**Issue by brazc** [heremaps/here-sdk-examples#56]
In the Explore Edition, there are icons appearing over certain POI (See link).
[Screenshot](
https://i.imgur.com/VGmy96f.jpg)

Is there a way to hide them?

**Comment by datasun** [comment]
Yes, the map is [fully customizable](https://developer.here.com/documentation/android-sdk-explore/4.5.1.0/dev_guide/topics/custom-map-styles.html#custom-map-styles).
