### ISSUE TITLE
HERE Mobile SDK UI Kit with HERE navigate SDK 4.5

### ISSUE THREAD

**Issue by ManikandanRavi** [heremaps/here-sdk-examples#57]
@MaKra  @tsteenbe  @datasun  @jehovahmidara 
Team, can you please help with the below questions
1. Can we use HERE Mobile SDK UI Kit with  HERE navigate SDK 4.5 version
2. Quickstart documentation of HERE Mobile SDK UI Kit  refers to use HERE-sdk.aar
But the aar files from HERE navigate or other SDK are named differently as heresdk-navigate-android-4.5.4.0.3646
3. Quickstart documentation of HERE Mobile, refers to use MSDKUILib-release.aar to run the example apps
How do we generate or get the MSDKUILib-release.aar

**Comment by datasun** [comment]
@ManikandanRavi, thanks for your questions. Happy to answer:

1. The MSDKUI Kit is not compatible with the HERE SDK.
2.  To use the MSDKUI Kit you must use the _Premium Edition_, other editions are not supported.
3. Follow these [steps](https://github.com/heremaps/msdkui-android/blob/master/Documentation/Guides/ContributionGuide.md#building-the-msdkui-library) to build the lib.

Hope this answers all. If not, please reply. Thank you.

**Comment by ManikandanRavi** [comment]
@datasun  thanks
