### ISSUE TITLE
How to use third party routing with HERE mobile SDK

### ISSUE THREAD

**Issue by ManikandanRavi** [heremaps/here-sdk-examples#58]
1.	Can you please help on the steps or documentation on how to bring in the data for third party routing, to use with HERE mobile SDK & generate the maneuvers
Can we feed the results of third party router, as waypoints to HERE SDK routing engine OR is there a better way

2.  Is there a limit on no of waypoints supported by the Routing engine.

**Comment by datasun** [comment]
@ManikandanRavi The MSDKUI it is not supported by the apps or the HERE SDK editions featured in this repo. You are referring to the _Premium Edition_: I am not aware of a limit for waypoints. And yes, you can use selected waypoint data from any other router, but the routes will be recalculated, of course. So you may need to adapt the route options to get similar results. In general, you can provide the coordinates plus several route options. Hope this helps, if not please leave a reply. Thank you.

**Comment by ManikandanRavi** [comment]
@datasun  thanks much for the response
