### ISSUE TITLE
addMapMarker3d Example

### ISSUE THREAD

**Issue by romandanylyk** [heremaps/here-sdk-examples#64]
Can you please add an example of how to properly add 3d markers on the map? 
I was trying to make it myself using the navigate edition SDK on android but faced some challenges with properly placing the object on the map.

Thanks in advance.

**Comment by datasun** [comment]
Yes, it will come soon. We can paste a link here once it's published. Stay tuned ... :)

**Comment by romandanylyk** [comment]
Really looking forward to that one. 
The link would be nice to have too.
Do you have any estimation dates on when I can expect the new example?

**Comment by romandanylyk** [comment]
@datasun Any progress on this one?
I would appreciate a simple example, how to create a mapMarker3d for a current position indicator.

**Comment by datasun** [comment]
Here's some code how you can add a 3D marker. It is not very different from normal 2D marker:

```
        // Place the files in the "assets" directory.
        String geometryFile = "abc.obj";
        String textureFile = "abc";
        MapMarker3DModel mapMarker3DModel = new MapMarker3DModel(geometryFile, textureFile);
        MapMarker3D mapMarker3D = new MapMarker3D(geoCoordinates, mapMarker3DModel);
        mapMarker3D.setScale(3);
        mapView.getMapScene().addMapMarker3d(mapMarker3D);
```

Maybe you can let me know the issues you have with adding the marker?

**Comment by romandanylyk** [comment]
I was mostly wondering how to set a texture on the model properly. 
Once I have a `.png` texture and a flat 3d model, what is the right way to specify a texture in `.obj` & `.mtl` files?

**Comment by datasun** [comment]
Thanks, this rather a question on the format, which is defined on `http://www.martinreddy.net/gfx/3d/OBJ.spec`. The .obj file can contain texture coordinates which indicate how the texture is wrapped around the model. Note that the HERE SDK does not yet support material files (*.mtl). Usually, you use tools such as Blender or open [https://threejs.org/editor/](https://threejs.org/editor/) to create the model. On this [screenshot](https://i.all3dp.com/cdn-cgi/image/fit=cover,w=1000,gravity=0.5x0.5,format=auto/wp-content/uploads/2017/09/27003032/blender_obj.png), you can see an example, how a texture is mapped onto a cube. 

A simple 2D square with a 1x1 rectangle PNG would look like this:

```
# A 2 x 2 square mapped with a 1 x 1 square
# texture stretched to fit the square exactly.
v  0.000000 2.000000 0.000000
v  0.000000 0.000000 0.000000
v  2.000000 0.000000 0.000000
v  2.000000 2.000000 0.000000
vt 0.000000 1.000000
vt 0.000000 0.000000
vt 1.000000 0.000000
vt 1.000000 1.000000
# 4 vertices
# The first number is the point, then the slash, and the second is the texture point
f 1/1 2/2 3/3 4/4
```

For this example, make sure to tilt the map to see it. You can also rotate the model programmatically - or even design the file in a way that is flat & centered on the origin.

For your use case, it's worth to mention that the `VisualNavigator` already contains a 3D position indicator asset you can use to track the user's location. However, in the future, the HERE SDK will also include a customizable location indicator class with predefined looks and accuracy halo.

**Comment by datasun** [comment]
Awesome. Thanks for the feedback. 

Closing the ticket.

**Comment by datasun** [comment]
As promised, the MapMarker example app was extended to show flat markers and 3D map markers with v4.6.5.0:

- Explore: https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/explore/android/MapMarker
- Navigate: https://github.com/heremaps/here-sdk-examples/tree/master/examples/latest/navigate/android/MapMarker

**Comment by romandanylyk** [comment]
Thanks, @datasun
