### ISSUE TITLE
Flat map image marker in Android Navigate Edition SDK

### ISSUE THREAD

**Issue by romandanylyk** [heremaps/here-sdk-examples#65]
I'm using the android Navigate Edition SDK and trying to add a flat image to the map, using the `MapMarker` with the `MapImage`, but it looks like it does not have the ability to flat the image, similar to Lite Edition via `MapMarkerImageStyle.setFlat(true)`.

Is there an ability to flat the image on the map using navigate edition SDK?
I need that one to display a custom current position indicator on the map, so it behaves similarly to 3d object while tilting the map. 
Thanks in advance.

**Comment by datasun** [comment]
For this purpose, the 3D map marker should be used. It's the only marker type that tilts with the map. The _Navigate Edition_ does not support flat 2D markers like the _Lite Edition_ does. On the other hand, the _Lite Edition_ does not support 3D markers.
