### ISSUE TITLE
builtin_types_conversion.dart "Method not found errors"

### ISSUE THREAD

**Issue by emilyjonesr** [heremaps/here-sdk-examples#67]
Hello!

I have been following the Get Started for HERE SDK for Flutter following the steps here: https://developer.here.com/documentation/flutter-sdk-explore/4.6.3.0/dev_guide/topics/quick-start.html#create-a-new-flutter-project-and-show-a-here-map

I have followed all of the steps, very carefully, multiple times, and while running on iOS simulator, after the Xcode build is done, I get the following errors from the builtin_types_conversion.dart file.
![Screen Shot 2021-03-08 at 2 51 29 PM](https://user-images.githubusercontent.com/58923694/110373735-d4f27b00-801d-11eb-8b41-786d73f1059f.png)

There are more but they all say the same "Method not found".

At the top of the builtin_types_conversion.dart file, it doesn't seem to recognize "intl" in the line: "import 'package:intl/locale.dart';"

I haven't touched the builtin_types_conversion.dart file and my pubspec.yaml file inside the here_sdk folder looks like this:
![Screen Shot 2021-03-08 at 3 04 26 PM](https://user-images.githubusercontent.com/58923694/110375232-b2f9f800-801f-11eb-8248-70f46980a02c.png)

The intl line under dependencies was originally just "intl:" when the problem started. I tried changing it to "intl: ^0.17.0" both with and without quotations and then running pub get, but that didn't work.

If you have any ideas on how to solve this or have any more insight into the problem, please let me know! Thanks!

**Comment by revrkk** [comment]
Yes, I'm also getting the same issue from yesterday.

**Comment by revrkk** [comment]
I tried the same in the previous flutter version 1.22.x and it worked.

**Comment by emilyjonesr** [comment]
Hi! Thanks for your help!
I tried changing to flutter 1.22.5, dart 2.10.4, Xcode 12.4, and android studio 4.1.1 as specified in the tutorial and restarting android studio and running flutter clean and flutter get pub a ton of times, but none of that has worked. Are there any extra steps you took to resolve the issue? Did you use these same versions? This is my pubspec.yaml now
![Screen Shot 2021-03-09 at 10 40 15 PM](https://user-images.githubusercontent.com/58923694/110572973-6fd77c00-8128-11eb-8c3f-9d7193c7fd26.png)

Thanks! @revrkk

**Comment by datasun** [comment]
@emilyjonesr Can you run `flutter doctor -v` from your terminal and paste the results here?

The minimum supported Flutter version is still 1.20.0, so actually, it should not be needed to use a newer version - although it should also work. Internally, we tested that the examples builds fine with 1.20.

**Comment by emilyjonesr** [comment]
@datasun Hi, yes here it is
![Screen Shot 2021-03-10 at 5 49 03 PM](https://user-images.githubusercontent.com/58923694/110708591-e9bf4200-81c8-11eb-96ed-bea97edf639d.png)

Thank you for your help.

**Comment by revrkk** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/12998431/110745093-d2756880-824b-11eb-890b-b733c8c60d70.png)

Here is mine. I'm using Flutter 1.22.2 and Dart 2.10.2.
I can run the app with this

**Comment by datasun** [comment]
Thanks! @revrkk - The Dart version you use (2.10.4)  is not matching your Flutter version (1.22.5), could you try to downgrade or upgrade?

**Comment by alexl246** [comment]
@datasun Am having exact same issue - same 'method not found' etc.

Have followed your suggestions and here is my flutter/ dart versions etc - any help is greatly appreciated 

<img width="567" alt="Screenshot 2021-03-19 at 00 54 51" src="https://user-images.githubusercontent.com/80589888/111716528-21c02800-884e-11eb-8e5c-7ff498c6c035.png">

**Comment by datasun** [comment]
@alexl246 You are using the preview / beta Flutter channel. Officially, we only support the stable channel, and also, only the minimum required version as listed in the user guide. However, with version 4.6.5.0 also newer versions should work, as we made a fix to the ffi dependency. For now, either wait for the next release, or downgrade to the minimum supported Flutter version.

**Comment by sajunt4** [comment]
Hi,
I've been given with HERE SDK v4.6.5.0 and the issue still pressent. It cames, in my case, from a dependency version missmatch.
In version v4.6.5.0 the SDK is forcing FFI version 0.1.3, that conflicts with many other packages that has already been updated to FFI 1.0.0.

For example, by using the open_file pluggin I've get this report while doing pub get:

`Because every version of here_sdk from path depends on ffi ^0.1.3 and open_file 3.1.0 depends on ffi ^1.0.0, here_sdk from path is incompatible with open_file 3.1.0.`

So I guess the only way to fix this is updating `builtin_types__conversion.dart` file to match the new ffi 1.0.0 standard.

**Comment by datasun** [comment]
@sajunt4 Thanks for reporting. We will look into this. Meanwhile, what exactly you mean by a dependency version missmatch. Can you maybe share the results you get from `flutter doctor -v`?

**Comment by sajunt4** [comment]
I mean that open_file, for example, requires ffi version 1.0.0, and Here SDK requires version 0.1.3. That makes both pluggins incompatible, so you cannot use Here SDK with other pluggins that have already been updated to ffi 1.0.0.

My flutter doctor:
`[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.21337.1010], locale en-US)
    • Flutter version 2.0.2 at D:\Programs\Flutter
    • Framework revision 8962f6dc68 (13 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\sajun\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\sajun\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • ONEPLUS A6000 (mobile) • 2634f08 • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)             • edge    • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!`

**Comment by datasun** [comment]
@sajunt4 Ok, thanks! 

Yes, basically, the HERE SDK uses FFI 0.1.3 (as it's indicated in the pubspec.yaml you can see in the plugin). Unfortunately, that means the SDK is not compatible with plugins that already use FFI 1.0

We plan to upgrade to FFI 1.0 with one of the next releases.

**Comment by sysquo-aditya** [comment]
Hey @datasun ,

With Firebase having changed so much, it has become irreplaceable for our app that is already in Production. A new feature requires a basic Map to be shown to the user and we looked at Here SDK for that.

It seems a lot of people are encountering this issue as well. Do you think it would be possible in near future to upgrade to using ffi 1.0.0? 
I am currently using Here SDK 4.7.5 and the app wouldn't build.

**Comment by datasun** [comment]
@sysquo-aditya Yes, we can confirm that FFI 1 support will come with the HERE SDK 4.8 release, which is supposed to be released in about four weeks.
