### ISSUE TITLE
Android: Tracking / Navigating on Navigate Edition SDK

### ISSUE THREAD

**Issue by romandanylyk** [heremaps/here-sdk-examples#68]
I'm trying to start tracking/navigating. The documentation specifies to the `VisualNavigator` class, using the `startRendering`
and `setCameraMode` functions. But it also says it will automatically tilt the camera to ~45 degrees and apply the default position indicator. 
It is all good, but how could I get more control over it? Say, use the custom position indicator or different tilt level. 
Similar to Premium SDK, once I start the tracking (with or without route), I would expect to only map camera move, while indicator coordinates should be updated along with the camera movement.

Please let me know if there is a way to make the camera move along the route/tracking, but still allows to set custom indicator and other camera options.

If not, I assume it is required to will to use `Navigator`, observe the `navigableLocation` (map matched location) and make the smooth camera movement by myself, probably using the `ValueAnimator` to compensate location jumps, by animating from the current location to a new one. 

I would appreciate any recommendation you have for that feature.

**Comment by datasun** [comment]
Hi @romandanylyk, if you do not set a `route` to the `VisualNavigator`, the camera settings like tilt and distance, can be set by you. Only when you set a route, the view settings will be changed. During turn-by-turn guidance, you cannot adjust the view, but we plan to provide more customization options with future HERE SDK versions.

Hope this helps.

**Comment by datasun** [comment]
@romandanylyk Good news, with HERE SDK 4.7.1 we plan to introduce the following methods to the VisualNavigator:

```
    public void setCameraDistanceInMeters(final double value);
    public void setCameraTiltInDegrees(final double value);
```

This will allow to customize the behavior a bit better.

**Comment by romandanylyk** [comment]
Great, looking forward for a 4.7.1 release

**Comment by romandanylyk** [comment]
Do you also plan to support dynamic zoom levels while navigating with a route, so that it smoothly changes based on approaching maneuver?

**Comment by datasun** [comment]
Yes, more updates are planned, including automatic zoom adjustments and customizable location indicator, but without a due date yet.
