### ISSUE TITLE
** BUILD FAILED ** - Method not found

### ISSUE THREAD

**Issue by alexl246** [heremaps/here-sdk-examples#69]
Have been trying to run example HERE Flutter application on VS Code - pressed to run and this issue is displayed. (Everything is up to date and refreshed etc). Have reinstalled pods etc as well. 

Appears to be the same root of issue

- Method not found: 'Utf8.toUtf8'. 
& 
- Method not found: 'free'. 

Code feedback is as follows...

<img width="923" alt="Screenshot 2021-03-19 at 00 59 27" src="https://user-images.githubusercontent.com/80589888/111716672-719eef00-884e-11eb-8194-461e304e1acf.png">

**Comment by datasun** [comment]
This is answered here: https://github.com/heremaps/here-sdk-examples/issues/67
