### ISSUE TITLE
Android Navigation - App crashes when minimize and open again by clicking on app icon

### ISSUE THREAD

**Issue by hanatharesh2712** [heremaps/here-sdk-examples#83]
When we start the app and click on the "Simulated Location" button it works properly. and then we minimize the app and open it again by clicking on the app icon it crashes the App randomly.  

Simulator: Pixel_XL_API_29

Error from log:

```
2021-06-02 20:03:19.114 17972-18060/com.navigationapp A/libc: FORTIFY: pthread_mutex_lock called on a destroyed mutex (0xd7018d20)
2021-06-02 20:03:19.114 17972-18060/com.navigationapp A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18060 (Thread-310), pid 17972 (s.navigationapp)
```

**Comment by datasun** [comment]
Thanks for raising. We will look into this.

**Comment by datasun** [comment]
@hanatharesh2712 We have not been able to reproduce this yet. It could be that you get a SIGBART when Android's TextToSpeech engine could not be initialized - in this case the example app [throws a Runtime exception](https://github.com/heremaps/here-sdk-examples/blob/9a751d9f03aa5b1250da4884f66e2c8855f3a1ea/examples/latest/navigate/android/Navigation/app/src/main/java/com/here/navigation/VoiceAssistant.java#L43) as the apps are not designed to cover any corner case that is not related to the HERE SDK.

It would help if you can send us the full log and the HERE SDK version you are using. Thanks!

**Comment by datasun** [comment]
Closing for now, if you can provide a log from the console output in Android Studio we can look into it.
