### ISSUE TITLE
OC Project use 4.x heresdk.framework

### ISSUE THREAD

**Issue by longlive68** [heremaps/here-sdk-examples#84]
The heresdk 4.x series built in Swift . now the project we work in is built in OC . it seems that it doesn`t work properly ? is the heresdk support OC soon ?

**Comment by datasun** [comment]
@longlive68 I guess OC stands for Objective-C? If so, we do not plan to add explicit support for Objective-C.

You cannot use Objective-C directly to access our HERE SDK APIs, which are written in Swift. But Xcode / iOS allows bridging, so you can use Objective-C, C++ and Swift in the same project, https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c.

The necessary Swift headers can be extracted from our framework file, if I am not wrong. But we have never tested this, so we cannot give any guarantee on this.
