### ISSUE TITLE
Xcode 11 : Module compiled with Swift 5.0.1 cannot be imported in Swift 5.1

### ISSUE THREAD

**Issue by hardikamal** [heremaps/here-sdk-examples#9]
Hi,

I am receiving compile time error "Xcode 11 : Module compiled with Swift 5.0.1 cannot be imported in Swift 5.1". How can I fix this?

Thanks

**Comment by MaKra** [comment]
We will release HERE SDK 4.1.4 that's compiled with Swift 5.1 and fixes this issue. 
Get an SDK update from developer.here.com to version 4.1.4 once it's available.
The release is planned for this week, most probably tonight or tomorrow.

**Comment by MaKra** [comment]
Version 4.1.4 that fixes your issue is now available via developer.here.com

**Comment by hardikamal** [comment]
@MaKra Is there a way to install via cocoapods?

**Comment by datasun** [comment]
@hardikamal Unfortunately, CocoaPods is not yet supported.
