### ISSUE TITLE
GeoJson support, Here Sdk Android 

### ISSUE THREAD

**Issue by cjurjiu** [heremaps/here-sdk-examples#91]
Hello, 

I can't find any reference on this: is displaying GeoJSON supported? If yes, in what tier of the Android SDK? Currently experimenting with Lite, though this is just for evaluating HERE maps as a solution for running our maps-enabled projects on devices with no Google Play Services support - so the plan is to switch to a paid version (depending on the outcome of our evaluation).

Not sure if this is the right place to ask this, thanks in advance :)

**Comment by datasun** [comment]
Hello @cjurjiu, GeoJSON is not directly supported as input value in any of our HERE SDK APIs, but the format is not so complex and it should be feasible to convert a list of coordinates into any of our Core types like GeoPolyline, GeoPolygon and so on. I would recommend to start with the _Explore Edition_ as the rendering capabilities are a bit more advanced. Please reply in case this is not a sufficient answer or in case you have more questions. Thanks!
