### ISSUE TITLE
Error while getting current location in Here SDK on Flutter

### ISSUE THREAD

**Issue by 0xmudur** [heremaps/here-sdk-examples#98]
When I calculate the route and start, I get an error like in the video below.

https://www.youtube.com/watch?v=RWV4Vren0Ao

How can I solve this situation?
How can I handle this situation in try-catch?

Also, there is no error in my console. All I see is the log "Are you off-road?" And the app crashes after a while.

Here version: 4.8.0.0

**Comment by datasun** [comment]
This looks like a random issue with the VisualNavigator. It should be fixed in the upcoming HERE SDK 4.9.1.0 which will be shipped next week if all goes well.
